# Generated by Django 6.0.4 on 2026-09-11 06:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PazarlamaProjesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Proje / Fırsat Kodu')),
                ('ad', models.CharField(max_length=200, verbose_name='Proje / Fırsat Başlığı')),
                ('musteri_adi', models.CharField(max_length=150, verbose_name='Hedef Müşteri / Firma')),
                ('hedef_ulke', models.CharField(max_length=100, verbose_name='Hedef Ülke / Pazar')),
                ('urun_grubu', models.CharField(choices=[('Sac Sekillendirme', 'Sac Şekillendirme'), ('Montaj ve Kaynak', 'Montaj ve Kaynak'), ('Kalıp & Fikstür', 'Kalıp & Fikstür'), ('Plastik Enjeksiyon', 'Plastik Enjeksiyon'), ('Batarya & EV Bilesenleri', 'Batarya & EV Bileşenleri'), ('Genel / Diger', 'Genel / Diğer')], default='Sac Sekillendirme', max_length=100, verbose_name='Ürün Grubu')),
                ('ilgili_fabrika', models.CharField(choices=[('Teleset 1 (Manisa)', 'Teleset 1 (Manisa)'), ('Teleset 2 (Manisa)', 'Teleset 2 (Manisa)'), ('Teleset 3 (Kocaeli)', 'Teleset 3 (Kocaeli)'), ('Teleset Otomotiv', 'Teleset Otomotiv'), ('Teleset Global', 'Teleset Global')], default='Teleset 1 (Manisa)', max_length=100, verbose_name='İlgili Fabrika')),
                ('sorumlu_pazarlama_uzmani', models.CharField(default='Pazarlama Uzmanı', max_length=100, verbose_name='Pazarlama Uzmanı (R)')),
                ('sorumlu_satis_muduru', models.CharField(default='Satış ve Pazarlama Müdürü', max_length=100, verbose_name='Satış & Pazarlama Müdürü (A)')),
                ('durum', models.CharField(choices=[('DEVAM_EDIYOR', 'Devam Ediyor'), ('TEKLIF_SURECINDE', ' Ürün Teklif Sürecine Aktarıldı'), ('BASARIYLA_KAPATILDI', 'Başarıyla Kapatıldı'), ('OLUMSUZ_KAPATILDI', 'Olumsuz Sonuçlandı / Kapatıldı'), ('ASKIDA', 'Askıda / Beklemede')], default='DEVAM_EDIYOR', max_length=30, verbose_name='Süreç Durumu')),
                ('guncel_adim_no', models.PositiveSmallIntegerField(default=1, verbose_name='Güncel Adım No')),
                ('tahmini_butce', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tahmini Bütçe (EUR/TL)')),
                ('beklenen_ciro', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Beklenen Yıllık Ciro (EUR)')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Genel Proje Notu / Özeti')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Pazarlama Projesi',
                'verbose_name_plural': 'Pazarlama Projeleri',
                'ordering': ['-guncelleme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SurecAdimTanimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adim_no', models.PositiveSmallIntegerField(unique=True, verbose_name='Adım Numarası')),
                ('baslik', models.CharField(max_length=255, verbose_name='Süreç Adımı Başlığı')),
                ('faaliyet_tanimi', models.TextField(verbose_name='Faaliyet Tanımı')),
                ('sorumlular_raci', models.TextField(verbose_name='Sorumlular (RACI)')),
                ('ilgili_dokumanlar', models.TextField(blank=True, null=True, verbose_name='İlgili Dokümanlar')),
                ('dijital_platformlar', models.TextField(blank=True, null=True, verbose_name='Dijital Platformlar')),
                ('karar_adimi_mi', models.BooleanField(default=False, verbose_name='Karar / Onay Adımı mı?')),
                ('faz', models.CharField(choices=[('FAZ1', 'Faz 1: Pazar & Strateji Planlama (Adım 1-6)'), ('FAZ2', 'Faz 2: Müşteri Teması & Talep Alma (Adım 7-10)'), ('FAZ3', 'Faz 3: Ön Mutabakat & Değerlendirme (Adım 11-12)'), ('FAZ4', 'Faz 4: Tedarikçi Onayı, Teklif & Kapanış (Adım 13-15)')], default='FAZ1', max_length=10, verbose_name='Süreç Fazı')),
            ],
            options={
                'verbose_name': 'Süreç Adım Tanımı',
                'verbose_name_plural': 'Süreç Adım Tanımları',
                'ordering': ['adim_no'],
            },
        ),
        migrations.CreateModel(
            name='ProjeGecmisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(max_length=255, verbose_name='Yapılan İşlem')),
                ('detay', models.TextField(blank=True, null=True, verbose_name='İşlem Detayı')),
                ('yapan', models.CharField(default='Sistem', max_length=100, verbose_name='İşlemi Yapan')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarihce_kayitlari', to='crm_takip.pazarlamaprojesi', verbose_name='Proje')),
            ],
            options={
                'verbose_name': 'Proje Geçmiş Logu',
                'verbose_name_plural': 'Proje Geçmiş Logları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='ProjeAdimKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('DEVAM_EDIYOR', 'Devam Ediyor / Aktif'), ('TAMAMLANDI', 'Tamamlandı (Onaylandı)'), ('REVIZYON_YONLENDIRILDI', 'Geriye Revizyona Gönderildi'), ('PAS_GECILDI', 'Pas Geçildi / Muaf')], default='BEKLIYOR', max_length=30, verbose_name='Durum')),
                ('tamamlayan', models.CharField(blank=True, max_length=100, null=True, verbose_name='İşlemi Yapan')),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('karar_sonucu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Verilen Karar')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Adım Notları / Gerekçe / Müşteri Geri Bildirimi')),
                ('dokuman_referansi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Doküman Linki / Referans No')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adim_kayitlari', to='crm_takip.pazarlamaprojesi', verbose_name='Proje')),
                ('adim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_takip.surecadimtanimi', verbose_name='Süreç Adımı')),
            ],
            options={
                'verbose_name': 'Proje Adım Kaydı',
                'verbose_name_plural': 'Proje Adım Kayıtları',
                'ordering': ['adim__adim_no'],
                'unique_together': {('proje', 'adim')},
            },
        ),
    ]
