# Generated by Django 6.0.4 on 2026-09-11 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HedefPazarKanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulke_kodu', models.CharField(max_length=10, unique=True, verbose_name='Ülke Kodu (ISO/Kısa)')),
                ('ulke_adi', models.CharField(max_length=100, verbose_name='Hedef Ülke Adı')),
                ('bayrak_emoji', models.CharField(default='', max_length=10, verbose_name='Bayrak')),
                ('oncelik_sinifi', models.CharField(default='Birincil Pazar', max_length=50, verbose_name='Pazar Sınıfı')),
                ('genel_gorunum', models.TextField(verbose_name='1. Ülke Genel Görünüm')),
                ('sektor_pazari', models.TextField(verbose_name='2. Beyaz Eşya / Sektör Pazarı')),
                ('one_cikan_sirketler', models.TextField(verbose_name='3. Öne Çıkan Şirketler & Müşteriler')),
                ('egilimler_ve_zorluklar', models.TextField(verbose_name='4. Eğilimler ve Zorluklar')),
                ('vergilendirme_ve_gumruk', models.TextField(verbose_name='5. Vergilendirme & Gümrükleme')),
                ('teleset_degerlendirmesi', models.TextField(verbose_name='6. Teleset Açısından Değerlendirme')),
                ('hedef_urunler', models.CharField(default='Kondenser, Kablo Grubu, Metal Parça, Kalıp', max_length=255, verbose_name='Hedef Ürün Grupları')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hedef Pazar Kanvası',
                'verbose_name_plural': 'Hedef Pazar Kanvasları',
                'ordering': ['ulke_adi'],
            },
        ),
        migrations.AlterField(
            model_name='pazarlamaprojesi',
            name='urun_grubu',
            field=models.CharField(choices=[('Kondenser & Sogutma', 'Kondenser & Soğutma'), ('Kablo Grubu', 'Kablo Grubu'), ('Metal Parca & Sac', 'Metal Parça & Sac Şekillendirme'), ('Kalıp & Fikstür', 'Kalıp & Fikstür'), ('Montaj ve Kaynak', 'Montaj ve Kaynak'), ('Plastik Enjeksiyon', 'Plastik Enjeksiyon'), ('Batarya & EV Bilesenleri', 'Batarya & EV Bileşenleri'), ('Genel / Diger', 'Genel / Diğer')], default='Metal Parca & Sac', max_length=100, verbose_name='Ürün Grubu'),
        ),
        migrations.AddField(
            model_name='pazarlamaprojesi',
            name='hedef_pazar_kanvasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeler', to='crm_takip.hedefpazarkanvas', verbose_name='İlişkili Ülke Kanvası'),
        ),
    ]
