# Generated by Django 6.0.4 on 2026-09-11 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0002_hedefpazarkanvas_alter_pazarlamaprojesi_urun_grubu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusteriKarti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='Müşteri Kodu (FRM-XX)')),
                ('ad', models.CharField(max_length=200, verbose_name='Firma Resmi Unvanı')),
                ('kisa_ad', models.CharField(max_length=50, verbose_name='Kısa / Marka Adı')),
                ('ulke', models.CharField(max_length=100, verbose_name='Ülke')),
                ('sehir', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir / Tesis Lokasyonu')),
                ('tier', models.CharField(choices=[('Tier 1 - KAM', '️ Tier 1 - KAM (Stratejik Ana Müşteri)'), ('Tier 2 - Growth', ' Tier 2 - Growth (Büyüme Odaklı Müşteri)'), ('Tier 3 - Standart', ' Tier 3 - Standart Müşteri')], default='Tier 1 - KAM', max_length=30, verbose_name='Müşteri Segmenti (Tier)')),
                ('strateji', models.CharField(choices=[('Protect', '️ Protect (İlişkiyi Koru & Derinleştir)'), ('Grow', ' Grow (Cüzdan Payını ve Hacmi Büyüt)'), ('Harvest', ' Harvest (Kârlılık Odaklı Yönet)')], default='Protect', max_length=30, verbose_name='CPM Stratejisi')),
                ('yillik_ciro_eur', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Yıllık Ciro (€)')),
                ('cuzdan_payi_yuzde', models.PositiveSmallIntegerField(default=50, verbose_name='Cüzdan Payı (SOW %)')),
                ('aktif_proje_sayisi', models.PositiveSmallIntegerField(default=1, verbose_name='Aktif Proje Sayısı')),
                ('kam_satis_lideri', models.CharField(default='Pazarlama Uzmanı', max_length=100, verbose_name='KAM Satış Lideri')),
                ('kam_muhendislik_lideri', models.CharField(default='Kalıp & Projeci Md.', max_length=100, verbose_name='KAM Projeci Lideri')),
                ('kam_kalite_lideri', models.CharField(default='Kalite Güvence Md.', max_length=100, verbose_name='KAM Kalite Lideri')),
                ('aktif_urunler', models.TextField(blank=True, null=True, verbose_name='Aktif Üretilen Parçalar / Ürünler')),
                ('sozlesme_durumu', models.CharField(default='STG-TL-001 Aktif', max_length=150, verbose_name='Sözleşme & Onay Durumu')),
                ('churn_riski', models.CharField(default='Düşük (Yeşil)', max_length=50, verbose_name='Müşteri Kayıp Riski')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Stratejik Notlar / Özet')),
            ],
            options={
                'verbose_name': 'Müşteri Kartı',
                'verbose_name_plural': 'Müşteri Kartları',
                'ordering': ['-yillik_ciro_eur'],
            },
        ),
        migrations.CreateModel(
            name='UrunGrubuKarti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Ürün Grubu Kodu')),
                ('baslik', models.CharField(max_length=150, verbose_name='Ürün Grubu Başlığı')),
                ('ikon', models.CharField(default='bi-box-seam', max_length=50, verbose_name='Bootstrap İkonu')),
                ('ana_fabrika', models.CharField(max_length=150, verbose_name='Ana Üretim Fabrikası')),
                ('kabiliyetler', models.TextField(verbose_name='Makine Parkı & Üretim Kabiliyetleri')),
                ('referans_parcalar', models.TextField(verbose_name='Referans Parçalar & Ürünler')),
                ('yillik_kapasite', models.CharField(max_length=150, verbose_name='Yıllık Üretim Kapasitesi')),
                ('hedef_sektorler', models.CharField(default='Beyaz Eşya, Otomotiv, İklimlendirme', max_length=255, verbose_name='Hedef Sektörler')),
                ('kalite_standartlari', models.CharField(default='ISO 9001, IATF 16949, ISO 14001, ISO 45001', max_length=255, verbose_name='Kalite Standartları')),
            ],
            options={
                'verbose_name': 'Ürün Grubu Kartı',
                'verbose_name_plural': 'Ürün Grubu Kartları',
                'ordering': ['kod'],
            },
        ),
        migrations.AlterField(
            model_name='hedefpazarkanvas',
            name='ulke_kodu',
            field=models.CharField(max_length=10, unique=True, verbose_name='Ülke Kodu'),
        ),
        migrations.AlterField(
            model_name='pazarlamaprojesi',
            name='urun_grubu',
            field=models.CharField(choices=[('Metal Parca & Sac', 'Metal Parça & Sac Şekillendirme'), ('Kondenser & Sogutma', 'Kondenser & Soğutma'), ('Kablo Grubu', 'Kablo Grubu & Demetleri'), ('Kalıp & Fikstür', 'Kalıp, Fikstür & Aparat'), ('Montaj ve Kaynak', 'Montaj ve Kaynak'), ('Plastik Enjeksiyon', 'Plastik Enjeksiyon'), ('Batarya & EV Bilesenleri', 'Batarya & EV Bileşenleri'), ('Genel / Diger', 'Genel / Diğer')], default='Metal Parca & Sac', max_length=100, verbose_name='Ürün Grubu'),
        ),
        migrations.AddField(
            model_name='pazarlamaprojesi',
            name='musteri_karti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeler', to='crm_takip.musterikarti', verbose_name='Müşteri Portföy Kartı'),
        ),
        migrations.AddField(
            model_name='pazarlamaprojesi',
            name='urun_grubu_karti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeler', to='crm_takip.urungrubukarti', verbose_name='İlişkili Ürün Grubu Kartı'),
        ),
    ]
