# Generated by Django 6.0.4 on 2026-09-11 07:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0003_musterikarti_urungrubukarti_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusteriIliskileriAdimTanimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adim_no', models.PositiveSmallIntegerField(unique=True, verbose_name='Adım Numarası')),
                ('baslik', models.CharField(max_length=255, verbose_name='Süreç Adımı Başlığı')),
                ('faaliyet_tanimi', models.TextField(verbose_name='Faaliyet Tanımı')),
                ('sorumlular', models.TextField(verbose_name='Sorumlular')),
                ('ilgili_dokumanlar', models.TextField(blank=True, null=True, verbose_name='İlgili Dokümanlar')),
                ('karar_adimi_mi', models.BooleanField(default=False, verbose_name='Karar / Kriter Adımı mı?')),
                ('faz', models.CharField(choices=[('FAZ1', 'Faz 1: Müşteri Tanımlama & İhtiyaç Analizi (Adım 1-4)'), ('FAZ2', 'Faz 2: Performans Ölçümü & Kriter Kontrolü (Adım 5-6)'), ('FAZ3', 'Faz 3: Memnuniyet Anketleri & İyileştirme Aksiyonları (Adım 7-9)'), ('FAZ4', 'Faz 4: YGG Raporlama & Dijital İzleme (Adım 10-11)')], default='FAZ1', max_length=10, verbose_name='Süreç Fazı')),
            ],
            options={
                'verbose_name': 'Müşteri İlişkileri Adım Tanımı',
                'verbose_name_plural': 'Müşteri İlişkileri Adım Tanımları',
                'ordering': ['adim_no'],
            },
        ),
        migrations.CreateModel(
            name='MusteriIliskileriSureci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Süreç Kodu')),
                ('ad', models.CharField(max_length=200, verbose_name='Süreç Başlığı / Konusu')),
                ('musteri_adi', models.CharField(max_length=150, verbose_name='Müşteri / Firma Adı')),
                ('donem', models.CharField(default='2026 Yıllık', max_length=50, verbose_name='İzleme Dönemi / Yıl')),
                ('ilgili_fabrika', models.CharField(choices=[('Teleset 1 (Manisa)', 'Teleset 1 (Manisa)'), ('Teleset 2 (Manisa)', 'Teleset 2 (Manisa)'), ('Teleset 3 (Kocaeli)', 'Teleset 3 (Kocaeli)'), ('Teleset Otomotiv', 'Teleset Otomotiv'), ('Teleset Global', 'Teleset Global')], default='Teleset 1 (Manisa)', max_length=100, verbose_name='İlgili Fabrika')),
                ('sorumlu_eys', models.CharField(default='EYS Sorumlusu', max_length=100, verbose_name='EYS Sorumlusu')),
                ('sorumlu_surec_sahibi', models.CharField(default='Süreç Sahibi / İyileştirme Ekibi', max_length=100, verbose_name='Süreç Sahibi / İyileştirme Ekibi')),
                ('durum', models.CharField(choices=[('DEVAM_EDIYOR', 'Devam Ediyor'), ('UYGUNSUZLUK_YONETIMINDE', 'Uygunsuzluk Yönetimi Sürecinde'), ('BASARIYLA_TAMAMLANDI', 'Başarıyla Tamamlandı'), ('ASKIDA', 'Askıda / Beklemede')], default='DEVAM_EDIYOR', max_length=30, verbose_name='Süreç Durumu')),
                ('guncel_adim_no', models.PositiveSmallIntegerField(default=1, verbose_name='Güncel Adım No')),
                ('memnuniyet_puani', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Müşteri Memnuniyet Puanı (0-100)')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Süreç Özeti / İlk Notlar')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('musteri_karti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musteri_iliskileri_surecleri', to='crm_takip.musterikarti', verbose_name='Müşteri Portföy Kartı')),
            ],
            options={
                'verbose_name': 'Müşteri İlişkileri Süreci',
                'verbose_name_plural': 'Müşteri İlişkileri Süreçleri',
                'ordering': ['-guncelleme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='MusteriIliskileriGecmisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(max_length=255, verbose_name='Yapılan İşlem')),
                ('detay', models.TextField(blank=True, null=True, verbose_name='İşlem Detayı')),
                ('yapan', models.CharField(default='Sistem', max_length=100, verbose_name='İşlemi Yapan')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('surec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarihce_kayitlari', to='crm_takip.musteriiliskilerisureci', verbose_name='Müşteri İlişkileri Süreci')),
            ],
            options={
                'verbose_name': 'Müşteri İlişkileri Geçmiş Logu',
                'verbose_name_plural': 'Müşteri İlişkileri Geçmiş Logları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='MusteriIliskileriAdimKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('DEVAM_EDIYOR', 'Devam Ediyor / Aktif'), ('TAMAMLANDI', 'Tamamlandı (Onaylandı)'), ('UYGUNSUZLUK_ACILDI', 'Uygunsuzluk Yönetimi Süreci Başlatıldı'), ('PAS_GECILDI', 'Pas Geçildi / Muaf')], default='BEKLIYOR', max_length=30, verbose_name='Durum')),
                ('tamamlayan', models.CharField(blank=True, max_length=100, null=True, verbose_name='İşlemi Yapan')),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('karar_sonucu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Verilen Karar (OK / NOK)')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Adım Notları / Değerlendirme / Aksiyon')),
                ('dokuman_referansi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Doküman Linki / Form No')),
                ('adim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_takip.musteriiliskileriadimtanimi', verbose_name='Süreç Adımı')),
                ('surec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adim_kayitlari', to='crm_takip.musteriiliskilerisureci', verbose_name='Müşteri İlişkileri Süreci')),
            ],
            options={
                'verbose_name': 'Müşteri İlişkileri Adım Kaydı',
                'verbose_name_plural': 'Müşteri İlişkileri Adım Kayıtları',
                'ordering': ['adim__adim_no'],
                'unique_together': {('surec', 'adim')},
            },
        ),
    ]
