# Generated by Django 6.0.4 on 2026-09-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0004_musteriiliskileriadimtanimi_musteriiliskilerisureci_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pazarlamaprojesi',
            options={'ordering': ['-guncelleme_tarihi'], 'verbose_name': 'Pazarlama Süreci', 'verbose_name_plural': 'Pazarlama Süreçleri'},
        ),
        migrations.AddField(
            model_name='projeadimkaydi',
            name='tamamlanan_dokumanlar',
            field=models.TextField(blank=True, default='', verbose_name='Tamamlanan / Tiklenen Dokümanlar'),
        ),
        migrations.AddField(
            model_name='projeadimkaydi',
            name='tamamlanan_platformlar',
            field=models.TextField(blank=True, default='', verbose_name='Kullanılan / Tiklenen Platformlar'),
        ),
    ]
