# Generated by Django 6.0.4 on 2026-09-11 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0005_alter_pazarlamaprojesi_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisSureciAdimTanimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adim_no', models.PositiveSmallIntegerField(unique=True, verbose_name='Adım Numarası')),
                ('baslik', models.CharField(max_length=255, verbose_name='Süreç Adımı Başlığı')),
                ('faaliyet_tanimi', models.TextField(verbose_name='Faaliyet Tanımı')),
                ('sorumlular', models.TextField(verbose_name='Sorumlular')),
                ('ilgili_dokumanlar', models.TextField(blank=True, null=True, verbose_name='İlgili Dokümanlar')),
                ('karar_adimi_mi', models.BooleanField(default=False, verbose_name='Karar / Kriter Adımı mı?')),
                ('faz', models.CharField(choices=[('FAZ1', 'Faz 1: Satış Stratejisi & Planlama (Adım 1-4)'), ('FAZ2', 'Faz 2: Müşteri Teması & İhtiyaç Değerlendirmesi (Adım 5-7)'), ('FAZ3', 'Faz 3: Müşteri İkna, Uygunsuzluk & Teklif Talebi (Adım 8-11)'), ('FAZ4', 'Faz 4: Kapanış, Performans & Sürekli İyileştirme (Adım 12-14)')], default='FAZ1', max_length=10, verbose_name='Süreç Fazı')),
            ],
            options={
                'verbose_name': 'Satış Süreci Adım Tanımı',
                'verbose_name_plural': 'Satış Süreci Adım Tanımları',
                'ordering': ['adim_no'],
            },
        ),
        migrations.CreateModel(
            name='SatisSureci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Süreç Kodu')),
                ('ad', models.CharField(max_length=200, verbose_name='Satış Projesi / Fırsat Başlığı')),
                ('musteri_adi', models.CharField(max_length=150, verbose_name='Müşteri / Firma Adı')),
                ('donem', models.CharField(default='2026 Yıllık', max_length=50, verbose_name='İzleme Dönemi / Yıl')),
                ('ilgili_fabrika', models.CharField(choices=[('Teleset 1 (Manisa)', 'Teleset 1 (Manisa)'), ('Teleset 2 (Manisa)', 'Teleset 2 (Manisa)'), ('Teleset 3 (Kocaeli)', 'Teleset 3 (Kocaeli)'), ('Teleset Otomotiv', 'Teleset Otomotiv'), ('Teleset Global', 'Teleset Global')], default='Teleset 1 (Manisa)', max_length=100, verbose_name='İlgili Fabrika')),
                ('urun_grubu', models.CharField(choices=[('Metal Parca & Sac', 'Metal Parça & Sac Şekillendirme'), ('Kondenser & Sogutma', 'Kondenser & Soğutma'), ('Kablo Grubu', 'Kablo Grubu & Demetleri'), ('Kalıp & Fikstür', 'Kalıp, Fikstür & Aparat'), ('Montaj ve Kaynak', 'Montaj ve Kaynak'), ('Plastik Enjeksiyon', 'Plastik Enjeksiyon'), ('Batarya & EV Bilesenleri', 'Batarya & EV Bileşenleri'), ('Genel / Diger', 'Genel / Diğer')], default='Metal Parca & Sac', max_length=100, verbose_name='Ürün Grubu')),
                ('sorumlu_satis_uzmani', models.CharField(default='Satış Uzmanı', max_length=100, verbose_name='Satış Uzmanı')),
                ('sorumlu_satis_yoneticisi', models.CharField(default='Satış Yöneticisi', max_length=100, verbose_name='Satış Yöneticisi')),
                ('durum', models.CharField(choices=[('DEVAM_EDIYOR', 'Devam Ediyor'), ('TEKLIF_SURECINDE', ' RFQ / Teklif Aşamasında'), ('BASARIYLA_TAMAMLANDI', 'Başarıyla Tamamlandı'), ('OLUMSUZ_KAPATILDI', 'Olumsuz Sonuçlandı'), ('ASKIDA', 'Askıda / Beklemede')], default='DEVAM_EDIYOR', max_length=30, verbose_name='Süreç Durumu')),
                ('guncel_adim_no', models.PositiveSmallIntegerField(default=1, verbose_name='Güncel Adım No')),
                ('tahmini_ciro', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Tahmini Yıllık Ciro (EUR)')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Süreç Özeti / İlk Notlar')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('musteri_karti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satis_surecleri', to='crm_takip.musterikarti', verbose_name='Müşteri Portföy Kartı')),
            ],
            options={
                'verbose_name': 'Satış Süreci',
                'verbose_name_plural': 'Satış Süreçleri',
                'ordering': ['-guncelleme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SatisSureciGecmisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(max_length=255, verbose_name='Yapılan İşlem')),
                ('detay', models.TextField(blank=True, null=True, verbose_name='İşlem Detayı')),
                ('yapan', models.CharField(default='Sistem', max_length=100, verbose_name='İşlemi Yapan')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('surec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarihce_kayitlari', to='crm_takip.satissureci', verbose_name='Satış Süreci')),
            ],
            options={
                'verbose_name': 'Satış Süreci Geçmiş Logu',
                'verbose_name_plural': 'Satış Süreci Geçmiş Logları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='SatisSureciAdimKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('DEVAM_EDIYOR', 'Devam Ediyor / Aktif'), ('TAMAMLANDI', 'Tamamlandı (Onaylandı)'), ('REVIZYON_YONLENDIRILDI', 'Geriye Revizyona Gönderildi'), ('UYGUNSUZLUK_ACILDI', 'Uygunsuzluk Yönetimi Süreci Başlatıldı'), ('PAS_GECILDI', 'Pas Geçildi / Muaf')], default='BEKLIYOR', max_length=30, verbose_name='Durum')),
                ('tamamlayan', models.CharField(blank=True, max_length=100, null=True, verbose_name='İşlemi Yapan')),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('karar_sonucu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Verilen Karar (OK / NOK)')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Adım Notları / Değerlendirme / Aksiyon')),
                ('dokuman_referansi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Doküman Linki / Form No')),
                ('surec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adim_kayitlari', to='crm_takip.satissureci', verbose_name='Satış Süreci')),
                ('adim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_takip.satissureciadimtanimi', verbose_name='Süreç Adımı')),
            ],
            options={
                'verbose_name': 'Satış Süreci Adım Kaydı',
                'verbose_name_plural': 'Satış Süreci Adım Kayıtları',
                'ordering': ['adim__adim_no'],
                'unique_together': {('surec', 'adim')},
            },
        ),
    ]
