# Generated by Django 6.0.4 on 2026-09-11 10:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0007_urunteklifadimtanimi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SozlesmeAdimTanimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adim_no', models.PositiveSmallIntegerField(unique=True, verbose_name='Adım Numarası')),
                ('baslik', models.CharField(max_length=255, verbose_name='Süreç Adımı Başlığı')),
                ('faaliyet_tanimi', models.TextField(verbose_name='Faaliyet Tanımı')),
                ('sorumlular', models.TextField(verbose_name='Sorumlular')),
                ('ilgili_dokumanlar', models.TextField(blank=True, null=True, verbose_name='İlgili Dokümanlar')),
                ('karar_adimi_mi', models.BooleanField(default=False, verbose_name='Karar / Kriter Adımı mı?')),
                ('faz', models.CharField(choices=[('FAZ1', 'Faz 1: Sözleşme Kabulü, Hukuki İnceleme & Uygunluk (Adım 1-4)'), ('FAZ2', 'Faz 2: Şartlar, Risk Değerlendirmesi & Yönetim Onayı (Adım 5-8)'), ('FAZ3', 'Faz 3: Müşteri Bilgilendirmesi, Müzakere & Karşılıklı İmza (Adım 9-12)'), ('FAZ4', 'Faz 4: EYS Entegrasyonu, Kapanış & Öğrenilmiş Dersler (Adım 13-15)')], default='FAZ1', max_length=10, verbose_name='Süreç Fazı')),
            ],
            options={
                'verbose_name': 'Sözleşme Adım Tanımı',
                'verbose_name_plural': 'Sözleşme Adım Tanımları',
                'ordering': ['adim_no'],
            },
        ),
        migrations.CreateModel(
            name='SozlesmeSureci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Sözleşme Süreç Kodu')),
                ('ad', models.CharField(max_length=200, verbose_name='Sözleşme Konusu / Başlığı')),
                ('musteri_adi', models.CharField(max_length=150, verbose_name='Müşteri / Firma Adı')),
                ('sozlesme_tipi', models.CharField(choices=[('GIZLILIK', 'Gizlilik Sözleşmesi (NDA)'), ('KALITE', 'Kalite Güvence Anlaşması (QAA)'), ('PLANLAMA_LOJISTIK', 'Planlama & Lojistik Sözleşmesi'), ('SURDURULEBILIRLIK', 'Sürdürülebilirlik & Çevre Protokolü'), ('SATIS', 'Genel Satış / Tedarik Çerçeve Sözleşmesi'), ('MAKINE_KALIP', 'Makine, Kalıp & Ekipman Yatırım Sözleşmesi'), ('DIGER', 'Diğer Ticari Sözleşmeler')], default='SATIS', max_length=40, verbose_name='Sözleşme Tipi')),
                ('donem', models.CharField(default='2026 Yıllık', max_length=50, verbose_name='Dönem / Yıl')),
                ('ilgili_fabrika', models.CharField(choices=[('Teleset 1 (Manisa)', 'Teleset 1 (Manisa)'), ('Teleset 2 (Manisa)', 'Teleset 2 (Manisa)'), ('Teleset 3 (Kocaeli)', 'Teleset 3 (Kocaeli)'), ('Teleset Otomotiv', 'Teleset Otomotiv'), ('Teleset Global', 'Teleset Global')], default='Teleset 1 (Manisa)', max_length=100, verbose_name='İlgili Fabrika')),
                ('baslangic_tarihi', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('sorumlu_satis_uzmani', models.CharField(default='Buse Nur Baltacıoğlu', max_length=100, verbose_name='Satış Uzmanı')),
                ('sorumlu_satis_yoneticisi', models.CharField(default='Satış Yöneticisi', max_length=100, verbose_name='Satış Yöneticisi')),
                ('sorumlu_fabrika_muduru', models.CharField(default='Fabrika Müdürü', max_length=100, verbose_name='Fabrika Müdürü')),
                ('sorumlu_hukuk', models.CharField(default='Şirket Hukuk Müşaviri', max_length=100, verbose_name='Şirket Hukuk Müşaviri / Avukat')),
                ('durum', models.CharField(choices=[('DEVAM_EDIYOR', 'Devam Ediyor'), ('HUKUKI_INCELEMEDE', 'Hukuki İncelemede'), ('YONETIM_ONAYINDA', 'Yönetim Onayında'), ('MUSTERI_MUZAKERESINDE', 'Müşteri Müzakeresinde'), ('BASARIYLA_TAMAMLANDI', 'Başarıyla İmzalandı & Tamamlandı'), ('OLUMSUZ_KAPATILDI', 'Mutabakat Sağlanamadı / İptal')], default='DEVAM_EDIYOR', max_length=30, verbose_name='Sözleşme Durumu')),
                ('guncel_adim_no', models.PositiveSmallIntegerField(default=1, verbose_name='Güncel Adım No')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Süreç Özeti / Başlangıç Notları')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('musteri_karti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sozlesme_surecleri', to='crm_takip.musterikarti', verbose_name='Müşteri Portföy Kartı')),
            ],
            options={
                'verbose_name': 'Sözleşme Değerlendirme Süreci',
                'verbose_name_plural': 'Sözleşme Değerlendirme Süreçleri',
                'ordering': ['-guncelleme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SozlesmeGecmisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(max_length=255, verbose_name='Yapılan İşlem')),
                ('detay', models.TextField(blank=True, null=True, verbose_name='İşlem Detayı')),
                ('yapan', models.CharField(default='Sistem', max_length=100, verbose_name='İşlemi Yapan')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('surec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarihce_kayitlari', to='crm_takip.sozlesmesureci', verbose_name='Sözleşme Süreci')),
            ],
            options={
                'verbose_name': 'Sözleşme Geçmiş Logu',
                'verbose_name_plural': 'Sözleşme Geçmiş Logları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='SozlesmeAdimKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('DEVAM_EDIYOR', 'Devam Ediyor / Aktif'), ('TAMAMLANDI', 'Tamamlandı (Onaylandı)'), ('MUZAKEREYE_YONLENDIRILDI', 'Müşteri Müzakeresine Yönlendirildi'), ('PAS_GECILDI', 'Pas Geçildi / Muaf')], default='BEKLIYOR', max_length=30, verbose_name='Durum')),
                ('tamamlayan', models.CharField(blank=True, max_length=100, null=True, verbose_name='İşlemi Yapan')),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('karar_sonucu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Verilen Karar (OK / NOK)')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Adım Notları / Değerlendirme / Hukuki Görüş')),
                ('dokuman_referansi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Doküman Linki / Form No')),
                ('adim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_takip.sozlesmeadimtanimi', verbose_name='Süreç Adımı')),
                ('surec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adim_kayitlari', to='crm_takip.sozlesmesureci', verbose_name='Sözleşme Süreci')),
            ],
            options={
                'verbose_name': 'Sözleşme Adım Kaydı',
                'verbose_name_plural': 'Sözleşme Adım Kayıtları',
                'ordering': ['adim__adim_no'],
                'unique_together': {('surec', 'adim')},
            },
        ),
    ]
