# Generated by Django 6.0.4 on 2026-09-11 10:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0008_sozlesmeadimtanimi_sozlesmesureci_sozlesmegecmislog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YeniUrunAdimTanimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adim_no', models.PositiveSmallIntegerField(unique=True, verbose_name='Adım Numarası')),
                ('baslik', models.CharField(max_length=255, verbose_name='Süreç Adımı Başlığı')),
                ('faaliyet_tanimi', models.TextField(verbose_name='Faaliyet Tanımı')),
                ('sorumlular', models.TextField(verbose_name='Sorumlular')),
                ('ilgili_dokumanlar', models.TextField(blank=True, null=True, verbose_name='İlgili Dokümanlar')),
                ('karar_adimi_mi', models.BooleanField(default=False, verbose_name='Karar / Onay Adımı mı?')),
                ('faz', models.CharField(choices=[('FAZ1', 'Faz 1: Talep, Ön Değerlendirme & Fizibilite (Adım 1-12)'), ('FAZ2', 'Faz 2: Proje Başlatma, Planlama & Tedarik Hazırlığı (Adım 13-19)'), ('FAZ3', 'Faz 3: Numune Üretimi, Doğrulama & Müşteri Onayı (Adım 20-30)'), ('FAZ4', 'Faz 4: Ön Seri Üretim, MSA, Yeterlilik & PPAP (Adım 31-39)'), ('FAZ5', 'Faz 5: Kapanış, Seri Üretime Geçiş & İyileştirme (Adım 40-45)')], default='FAZ1', max_length=10, verbose_name='Süreç Fazı')),
            ],
            options={
                'verbose_name': 'Yeni Ürün Adım Tanımı',
                'verbose_name_plural': 'Yeni Ürün Adım Tanımları',
                'ordering': ['adim_no'],
            },
        ),
        migrations.CreateModel(
            name='YeniUrunDevreyeAlmaSureci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='NPI Proje Kodu')),
                ('ad', models.CharField(max_length=200, verbose_name='Ürün / Proje Adı')),
                ('musteri_adi', models.CharField(max_length=150, verbose_name='Müşteri / Firma Adı')),
                ('urun_grubu', models.CharField(choices=[('Kondenser & Sogutma', 'Kondenser & Soğutma Grubu'), ('Metal Parca & Sac', 'Metal Parça & Sac Şekillendirme'), ('Kablo Grubu', 'Kablo Grubu & Demetleri'), ('Kalıp & Fikstür', 'Kalıp, Fikstür & Aparat'), ('Montaj ve Kaynak', 'Montaj ve Kaynak'), ('Plastik Enjeksiyon', 'Plastik Enjeksiyon'), ('Batarya & EV Bilesenleri', 'Batarya & EV Bileşenleri'), ('Genel / Diger', 'Genel / Diğer')], default='Kondenser & Sogutma', max_length=100, verbose_name='Ürün Grubu')),
                ('ilgili_fabrika', models.CharField(choices=[('Teleset 1 (Manisa)', 'Teleset 1 (Manisa)'), ('Teleset 2 (Manisa)', 'Teleset 2 (Manisa)'), ('Teleset 3 (Kocaeli)', 'Teleset 3 (Kocaeli)'), ('Teleset Otomotiv', 'Teleset Otomotiv'), ('Teleset Global', 'Teleset Global')], default='Teleset 1 (Manisa)', max_length=100, verbose_name='Üretim Fabrikası')),
                ('parca_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Müşteri / Teleset Parça Kodu')),
                ('hedef_seri_uretim_tarihi', models.DateField(blank=True, null=True, verbose_name='Hedef Seri Üretime Geçiş Tarihi')),
                ('yillik_hedef_adet', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yıllık Hedef Adet')),
                ('sorumlu_proje_lideri', models.CharField(default='Proje Sorumlusu', max_length=100, verbose_name='Proje Sorumlusu')),
                ('sorumlu_fabrika_muduru', models.CharField(default='Fabrika Müdürü', max_length=100, verbose_name='Fabrika Müdürü')),
                ('sorumlu_satis_analiz', models.CharField(default='Satış-Analiz Sorumlusu', max_length=100, verbose_name='Satış-Analiz Sorumlusu')),
                ('sorumlu_kalite', models.CharField(default='Kalite Sorumlusu', max_length=100, verbose_name='Kalite Sorumlusu')),
                ('durum', models.CharField(choices=[('DEVAM_EDIYOR', 'Devam Ediyor'), ('UYGUNSUZLUK_YONETIMINDE', '️ DÖF / Uygunsuzluk Sürecinde'), ('REVIZYONDA', ' Revizyon Aşamasında'), ('BASARIYLA_TAMAMLANDI', ' Başarıyla Seri Üretime Alındı & Kapatıldı'), ('OLUMSUZ_KAPATILDI', ' Müşteri Onayı Alınamadı / Kapatıldı'), ('ASKIDA', 'Askıda / Beklemede')], default='DEVAM_EDIYOR', max_length=35, verbose_name='Süreç Durumu')),
                ('guncel_adim_no', models.PositiveSmallIntegerField(default=1, verbose_name='Güncel Adım No')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Proje Kapsamı & Notlar')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('musteri_karti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yeni_urun_surecleri', to='crm_takip.musterikarti', verbose_name='Müşteri Portföy Kartı')),
                ('urun_grubu_karti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yeni_urun_surecleri', to='crm_takip.urungrubukarti', verbose_name='İlişkili Ürün Grubu Kartı')),
            ],
            options={
                'verbose_name': 'Yeni Ürün Devreye Alma Süreci',
                'verbose_name_plural': 'Yeni Ürün Devreye Alma Süreçleri',
                'ordering': ['-guncelleme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='YeniUrunGecmisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(max_length=255, verbose_name='Yapılan İşlem')),
                ('detay', models.TextField(blank=True, null=True, verbose_name='İşlem Detayı')),
                ('yapan', models.CharField(default='Sistem', max_length=100, verbose_name='İşlemi Yapan')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('surec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarihce_kayitlari', to='crm_takip.yeniurundevreyealmasureci', verbose_name='Yeni Ürün Süreci')),
            ],
            options={
                'verbose_name': 'Yeni Ürün Geçmiş Logu',
                'verbose_name_plural': 'Yeni Ürün Geçmiş Logları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='YeniUrunAdimKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('DEVAM_EDIYOR', 'Devam Ediyor / Aktif'), ('TAMAMLANDI', 'Tamamlandı (Onaylandı)'), ('REVIZYON_YONLENDIRILDI', 'Geriye Revizyona Gönderildi'), ('PAS_GECILDI', 'Pas Geçildi / Muaf')], default='BEKLIYOR', max_length=30, verbose_name='Durum')),
                ('tamamlayan', models.CharField(blank=True, max_length=100, null=True, verbose_name='İşlemi Yapan')),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('karar_sonucu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Verilen Karar (OK / NOK / EVET / HAYIR)')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Adım Notları / Değerlendirme / Teknik Çıktı')),
                ('dokuman_referansi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Doküman Linki / Form No')),
                ('adim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_takip.yeniurunadimtanimi', verbose_name='Süreç Adımı')),
                ('surec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adim_kayitlari', to='crm_takip.yeniurundevreyealmasureci', verbose_name='Yeni Ürün Süreci')),
            ],
            options={
                'verbose_name': 'Yeni Ürün Adım Kaydı',
                'verbose_name_plural': 'Yeni Ürün Adım Kayıtları',
                'ordering': ['adim__adim_no'],
                'unique_together': {('surec', 'adim')},
            },
        ),
    ]
