# Generated by Django 6.0.4 on 2026-09-11 11:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0009_yeniurunadimtanimi_yeniurundevreyealmasureci_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuhendislikDegisikligiAdimTanimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adim_no', models.PositiveSmallIntegerField(unique=True, verbose_name='Adım Numarası')),
                ('baslik', models.CharField(max_length=255, verbose_name='Süreç Adımı Başlığı')),
                ('faaliyet_tanimi', models.TextField(verbose_name='Faaliyet Tanımı')),
                ('sorumlular', models.TextField(verbose_name='Sorumlular')),
                ('ilgili_dokumanlar', models.TextField(blank=True, null=True, verbose_name='İlgili Dokümanlar')),
                ('karar_adimi_mi', models.BooleanField(default=False, verbose_name='Karar / Kriter Adımı mı?')),
                ('faz', models.CharField(choices=[('FAZ1', 'Faz 1: Değişiklik Talebi, Değerlendirme, Maliyet & Müşteri Onayı (Adım 1-11)'), ('FAZ2', 'Faz 2: Teknik Hazırlık, BOM, Proses & Numune Üretimi (Adım 12-18)'), ('FAZ3', 'Faz 3: Numune ISIR Ölçümü, Müşteri Onayı & Ön Seri Üretim (Adım 19-27)'), ('FAZ4', 'Faz 4: Seri Üretime Geçiş, Dokümantasyon, Kapanış & İyileştirme (Adım 28-34)')], default='FAZ1', max_length=10, verbose_name='Süreç Fazı')),
            ],
            options={
                'verbose_name': 'Mühendislik Değişikliği Adım Tanımı',
                'verbose_name_plural': 'Mühendislik Değişikliği Adım Tanımları',
                'ordering': ['adim_no'],
            },
        ),
        migrations.CreateModel(
            name='MuhendislikDegisikligiSureci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Değişiklik Kodu (ECO)')),
                ('ad', models.CharField(max_length=200, verbose_name='Değişiklik Konusu / Başlığı')),
                ('musteri_adi', models.CharField(max_length=150, verbose_name='Müşteri / Firma Adı')),
                ('parca_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parça Kodu / No')),
                ('revizyon_no', models.CharField(default='Rev.01', max_length=50, verbose_name='Revizyon No')),
                ('degisiklik_nedeni', models.CharField(choices=[('MUSTERI_TALEBI', 'Müşteri Revizyon Talebi'), ('MALIYET_IYILESTIRME', 'Maliyet İyileştirme & VAVE'), ('KALITE_IYILESTIRME', 'Kalite & DÖF Kaynaklı İyileştirme'), ('HAMMADDE_TEDARIK', 'Hammadde / Tedarikçi Değişikliği'), ('IC_PROSES', 'İç Proses & Makine Parkuru İyileştirme'), ('STANDART_MEVZUAT', 'Standart / Mevzuat Değişikliği')], default='MUSTERI_TALEBI', max_length=40, verbose_name='Değişiklik Nedeni')),
                ('urun_grubu', models.CharField(choices=[('Metal Parca & Sac', 'Metal Parça & Sac Şekillendirme'), ('Kondenser & Sogutma', 'Kondenser & Soğutma'), ('Kablo Grubu', 'Kablo Grubu & Demetleri'), ('Kalıp & Fikstür', 'Kalıp, Fikstür & Aparat'), ('Montaj ve Kaynak', 'Montaj ve Kaynak'), ('Plastik Enjeksiyon', 'Plastik Enjeksiyon'), ('Batarya & EV Bilesenleri', 'Batarya & EV Bileşenleri'), ('Genel / Diger', 'Genel / Diğer')], default='Metal Parca & Sac', max_length=100, verbose_name='Ürün Grubu')),
                ('ilgili_fabrika', models.CharField(choices=[('Teleset 1 (Manisa)', 'Teleset 1 (Manisa)'), ('Teleset 2 (Manisa)', 'Teleset 2 (Manisa)'), ('Teleset 3 (Kocaeli)', 'Teleset 3 (Kocaeli)'), ('Teleset Otomotiv', 'Teleset Otomotiv'), ('Teleset Global', 'Teleset Global')], default='Teleset 1 (Manisa)', max_length=100, verbose_name='İlgili Fabrika')),
                ('hedef_tamamlanma_tarihi', models.DateField(blank=True, null=True, verbose_name='Hedef Tamamlanma Tarihi')),
                ('sorumlu_proje_sorumlusu', models.CharField(default='Buse Nur Baltacıoğlu', max_length=100, verbose_name='Proje Sorumlusu (R)')),
                ('sorumlu_fabrika_muduru', models.CharField(default='Serdar Acar', max_length=100, verbose_name='Fabrika Müdürü (A)')),
                ('sorumlu_satis_analiz', models.CharField(default='Hakan Yılmaz', max_length=100, verbose_name='Satış-Analiz Sorumlusu (C)')),
                ('sorumlu_kalite', models.CharField(default='Ahmet Yurt', max_length=100, verbose_name='Kalite Sorumlusu (C)')),
                ('durum', models.CharField(choices=[('DEVAM_EDIYOR', 'Devam Ediyor'), ('YENI_URUN_SURECINE_AKTARILDI', 'Yeni Ürün Devreye Alma Sürecine Aktarıldı'), ('REVIZYONDA', 'Revizyon Aşamasında'), ('BASARIYLA_TAMAMLANDI', 'Başarıyla Seri Üretime Alındı & Kapatıldı'), ('OLUMSUZ_KAPATILDI', 'İptal / Olumsuz Kapatıldı')], default='DEVAM_EDIYOR', max_length=40, verbose_name='Süreç Durumu')),
                ('guncel_adim_no', models.PositiveSmallIntegerField(default=1, verbose_name='Güncel Adım No')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Değişiklik Özeti / Başlangıç Notları')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('musteri_karti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muhendislik_degisiklikleri', to='crm_takip.musterikarti', verbose_name='Müşteri Portföy Kartı')),
            ],
            options={
                'verbose_name': 'Mühendislik Değişikliği Süreci',
                'verbose_name_plural': 'Mühendislik Değişikliği Süreçleri',
                'ordering': ['-guncelleme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='MuhendislikDegisikligiGecmisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(max_length=255, verbose_name='Yapılan İşlem')),
                ('detay', models.TextField(blank=True, null=True, verbose_name='İşlem Detayı')),
                ('yapan', models.CharField(default='Sistem', max_length=100, verbose_name='İşlemi Yapan')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('surec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarihce_kayitlari', to='crm_takip.muhendislikdegisikligisureci', verbose_name='Mühendislik Değişikliği Süreci')),
            ],
            options={
                'verbose_name': 'Mühendislik Değişikliği Geçmiş Logu',
                'verbose_name_plural': 'Mühendislik Değişikliği Geçmiş Logları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='MuhendislikDegisikligiAdimKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('DEVAM_EDIYOR', 'Devam Ediyor / Aktif'), ('TAMAMLANDI', 'Tamamlandı (Onaylandı)'), ('REVIZYON_YONLENDIRILDI', 'Geriye Revizyona Gönderildi'), ('PAS_GECILDI', 'Pas Geçildi / Muaf')], default='BEKLIYOR', max_length=30, verbose_name='Durum')),
                ('tamamlayan', models.CharField(blank=True, max_length=100, null=True, verbose_name='İşlemi Yapan')),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('karar_sonucu', models.CharField(blank=True, max_length=150, null=True, verbose_name='Verilen Karar')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Adım Notları / Değerlendirme / Teknik Çıktı')),
                ('dokuman_referansi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Doküman Linki / Form No')),
                ('adim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_takip.muhendislikdegisikligiadimtanimi', verbose_name='Süreç Adımı')),
                ('surec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adim_kayitlari', to='crm_takip.muhendislikdegisikligisureci', verbose_name='Mühendislik Değişikliği Süreci')),
            ],
            options={
                'verbose_name': 'Mühendislik Değişikliği Adım Kaydı',
                'verbose_name_plural': 'Mühendislik Değişikliği Adım Kayıtları',
                'ordering': ['adim__adim_no'],
                'unique_together': {('surec', 'adim')},
            },
        ),
    ]
