# Generated by Django 6.0.4 on 2026-09-11 11:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0010_muhendislikdegisikligiadimtanimi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrototipAdimTanimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adim_no', models.PositiveSmallIntegerField(unique=True, verbose_name='Adım Numarası')),
                ('baslik', models.CharField(max_length=255, verbose_name='Süreç Adımı Başlığı')),
                ('faaliyet_tanimi', models.TextField(verbose_name='Faaliyet Tanımı')),
                ('sorumlular', models.TextField(verbose_name='Sorumlular')),
                ('ilgili_dokumanlar', models.TextField(blank=True, null=True, verbose_name='İlgili Dokümanlar')),
                ('karar_adimi_mi', models.BooleanField(default=False, verbose_name='Karar / Kriter Adımı mı?')),
                ('faz', models.CharField(choices=[('FAZ1', 'Faz 1: Talep, Ön Değerlendirme & Müşteri Başlangıç Onayı (Adım 1-9)'), ('FAZ2', 'Faz 2: Teknik Hazırlık, Tedarik & ERP Numune BOM (Adım 10-14)'), ('FAZ3', 'Faz 3: Prototip İmalatı, ISIR Ölçümü & Müşteri Doğrulaması (Adım 15-20)'), ('FAZ4', 'Faz 4: Reçete Kontrolü, Kapanış & Öğrenilmiş Dersler (Adım 21-23)')], default='FAZ1', max_length=10, verbose_name='Süreç Fazı')),
            ],
            options={
                'verbose_name': 'Prototip Adım Tanımı',
                'verbose_name_plural': 'Prototip Adım Tanımları',
                'ordering': ['adim_no'],
            },
        ),
        migrations.AlterField(
            model_name='hedefpazarkanvas',
            name='bayrak_emoji',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Bayrak'),
        ),
        migrations.AlterField(
            model_name='musteriiliskilerisureci',
            name='durum',
            field=models.CharField(choices=[('DEVAM_EDIYOR', 'Devam Ediyor'), ('UYGUNSUZLUK_YONETIMINDE', 'Uygunsuzluk Yönetimi Sürecinde'), ('BASARIYLA_TAMAMLANDI', 'Başarıyla Tamamlandı'), ('ASKIDA', 'Askıda / Beklemede')], default='DEVAM_EDIYOR', max_length=30, verbose_name='Süreç Durumu'),
        ),
        migrations.AlterField(
            model_name='musterikarti',
            name='strateji',
            field=models.CharField(choices=[('Protect', 'Protect (İlişkiyi Koru & Derinleştir)'), ('Grow', 'Grow (Cüzdan Payını ve Hacmi Büyüt)'), ('Harvest', 'Harvest (Kârlılık Odaklı Yönet)')], default='Protect', max_length=30, verbose_name='CPM Stratejisi'),
        ),
        migrations.AlterField(
            model_name='musterikarti',
            name='tier',
            field=models.CharField(choices=[('Tier 1 - KAM', 'Tier 1 - KAM (Stratejik Ana Müşteri)'), ('Tier 2 - Growth', 'Tier 2 - Growth (Büyüme Odaklı Müşteri)'), ('Tier 3 - Standart', 'Tier 3 - Standart Müşteri')], default='Tier 1 - KAM', max_length=30, verbose_name='Müşteri Segmenti (Tier)'),
        ),
        migrations.AlterField(
            model_name='pazarlamaprojesi',
            name='durum',
            field=models.CharField(choices=[('DEVAM_EDIYOR', 'Devam Ediyor'), ('TEKLIF_SURECINDE', 'Ürün Teklif Sürecine Aktarıldı'), ('BASARIYLA_KAPATILDI', 'Başarıyla Kapatıldı'), ('OLUMSUZ_KAPATILDI', 'Olumsuz Sonuçlandı / Kapatıldı'), ('ASKIDA', 'Askıda / Beklemede')], default='DEVAM_EDIYOR', max_length=30, verbose_name='Süreç Durumu'),
        ),
        migrations.AlterField(
            model_name='yeniurundevreyealmasureci',
            name='durum',
            field=models.CharField(choices=[('DEVAM_EDIYOR', 'Devam Ediyor'), ('UYGUNSUZLUK_YONETIMINDE', 'DÖF / Uygunsuzluk Sürecinde'), ('REVIZYONDA', 'Revizyon Aşamasında'), ('BASARIYLA_TAMAMLANDI', 'Başarıyla Seri Üretime Alındı & Kapatıldı'), ('OLUMSUZ_KAPATILDI', 'Müşteri Onayı Alınamadı / Kapatıldı'), ('ASKIDA', 'Askıda / Beklemede')], default='DEVAM_EDIYOR', max_length=35, verbose_name='Süreç Durumu'),
        ),
        migrations.CreateModel(
            name='PrototipSureci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Prototip Kodu (PRT)')),
                ('ad', models.CharField(max_length=200, verbose_name='Prototip Konusu / Proje Adı')),
                ('musteri_adi', models.CharField(max_length=150, verbose_name='Müşteri / Firma Adı')),
                ('parca_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parça / Numune Kodu')),
                ('revizyon_no', models.CharField(default='Rev.01', max_length=50, verbose_name='Revizyon No')),
                ('prototip_tipi', models.CharField(choices=[('YENI_TASARIM', 'Yeni Tasarım Prototipi'), ('MALZEME_DENEME', 'Malzeme / Hammadde Değişikliği Prototipi'), ('VAVE_MALIYET', 'Maliyet İyileştirme / VAVE Prototipi'), ('MUSTERI_TEST', 'Müşteri Fonksiyonel Test Prototipi'), ('PROSES_DENEME', 'İç Proses & Kalıp Doğrulama Prototipi')], default='YENI_TASARIM', max_length=40, verbose_name='Prototip Tipi')),
                ('urun_grubu', models.CharField(choices=[('Metal Parca & Sac', 'Metal Parça & Sac Şekillendirme'), ('Kondenser & Sogutma', 'Kondenser & Soğutma'), ('Kablo Grubu', 'Kablo Grubu & Demetleri'), ('Kalıp & Fikstür', 'Kalıp, Fikstür & Aparat'), ('Montaj ve Kaynak', 'Montaj ve Kaynak'), ('Plastik Enjeksiyon', 'Plastik Enjeksiyon'), ('Batarya & EV Bilesenleri', 'Batarya & EV Bileşenleri'), ('Genel / Diger', 'Genel / Diğer')], default='Metal Parca & Sac', max_length=100, verbose_name='Ürün Grubu')),
                ('ilgili_fabrika', models.CharField(choices=[('Teleset 1 (Manisa)', 'Teleset 1 (Manisa)'), ('Teleset 2 (Manisa)', 'Teleset 2 (Manisa)'), ('Teleset 3 (Kocaeli)', 'Teleset 3 (Kocaeli)'), ('Teleset Otomotiv', 'Teleset Otomotiv'), ('Teleset Global', 'Teleset Global')], default='Teleset 1 (Manisa)', max_length=100, verbose_name='İlgili Fabrika')),
                ('hedef_tamamlanma_tarihi', models.DateField(blank=True, null=True, verbose_name='Hedef Tamamlanma Tarihi')),
                ('sorumlu_proje_sorumlusu', models.CharField(default='Buse Nur Baltacıoğlu', max_length=100, verbose_name='Proje Sorumlusu (R)')),
                ('sorumlu_fabrika_muduru', models.CharField(default='Serdar Acar', max_length=100, verbose_name='Fabrika Müdürü (A)')),
                ('sorumlu_satis_analiz', models.CharField(default='Hakan Yılmaz', max_length=100, verbose_name='Satış-Analiz Sorumlusu (C)')),
                ('sorumlu_kalite', models.CharField(default='Ahmet Yurt', max_length=100, verbose_name='Kalite Sorumlusu (C)')),
                ('durum', models.CharField(choices=[('DEVAM_EDIYOR', 'Devam Ediyor'), ('YENI_URUN_SURECINE_AKTARILDI', 'Yeni Ürün Devreye Alma Sürecine Aktarıldı'), ('REVIZYONDA', 'Revizyon Aşamasında'), ('BASARIYLA_TAMAMLANDI', 'Başarıyla Tamamlandı & Arşivlendi'), ('OLUMSUZ_KAPATILDI', 'Müşteri Onayı Alınamadı / İptal')], default='DEVAM_EDIYOR', max_length=40, verbose_name='Süreç Durumu')),
                ('guncel_adim_no', models.PositiveSmallIntegerField(default=1, verbose_name='Güncel Adım No')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Prototip Özeti / Başlangıç Notları')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('musteri_karti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prototip_surecleri', to='crm_takip.musterikarti', verbose_name='Müşteri Portföy Kartı')),
            ],
            options={
                'verbose_name': 'Prototip Süreci',
                'verbose_name_plural': 'Prototip Süreçleri',
                'ordering': ['-guncelleme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='PrototipGecmisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(max_length=255, verbose_name='Yapılan İşlem')),
                ('detay', models.TextField(blank=True, null=True, verbose_name='İşlem Detayı')),
                ('yapan', models.CharField(default='Sistem', max_length=100, verbose_name='İşlemi Yapan')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('surec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarihce_kayitlari', to='crm_takip.prototipsureci', verbose_name='Prototip Süreci')),
            ],
            options={
                'verbose_name': 'Prototip Geçmiş Logu',
                'verbose_name_plural': 'Prototip Geçmiş Logları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='PrototipAdimKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('DEVAM_EDIYOR', 'Devam Ediyor / Aktif'), ('TAMAMLANDI', 'Tamamlandı (Onaylandı)'), ('REVIZYON_YONLENDIRILDI', 'Geriye Revizyona Gönderildi'), ('PAS_GECILDI', 'Pas Geçildi / Muaf')], default='BEKLIYOR', max_length=30, verbose_name='Durum')),
                ('tamamlayan', models.CharField(blank=True, max_length=100, null=True, verbose_name='İşlemi Yapan')),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('karar_sonucu', models.CharField(blank=True, max_length=150, null=True, verbose_name='Verilen Karar')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Adım Notları / Değerlendirme / Teknik Çıktı')),
                ('dokuman_referansi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Doküman Linki / Form No')),
                ('adim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_takip.prototipadimtanimi', verbose_name='Süreç Adımı')),
                ('surec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adim_kayitlari', to='crm_takip.prototipsureci', verbose_name='Prototip Süreci')),
            ],
            options={
                'verbose_name': 'Prototip Adım Kaydı',
                'verbose_name_plural': 'Prototip Adım Kayıtları',
                'ordering': ['adim__adim_no'],
                'unique_together': {('surec', 'adim')},
            },
        ),
    ]
