# Generated by Django 6.0.4 on 2026-09-11 12:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0011_prototipadimtanimi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EOPSurecAdimTanimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adim_no', models.PositiveSmallIntegerField(unique=True, verbose_name='Adım Numarası')),
                ('baslik', models.CharField(max_length=255, verbose_name='Süreç Adımı Başlığı')),
                ('faaliyet_tanimi', models.TextField(verbose_name='Faaliyet Tanımı')),
                ('sorumlular', models.CharField(max_length=255, verbose_name='Sorumlular')),
                ('ilgili_dokumanlar', models.TextField(blank=True, null=True, verbose_name='İlgili Dokümanlar')),
                ('karar_adimi_mi', models.BooleanField(default=False, verbose_name='Karar / Onay Adımı mı?')),
                ('faz', models.CharField(choices=[('FAZ1', 'Faz 1: EOP Bildirimi & Talep Analizi (Adım 1-2)'), ('FAZ2', 'Faz 2: Stok & Üretim Varlıkları Tasfiyesi (Adım 3-4)'), ('FAZ3', 'Faz 3: Sistem Kapatma & Süreç Kapanışı (Adım 5-6)')], default='FAZ1', max_length=10, verbose_name='Süreç Fazı')),
            ],
            options={
                'verbose_name': 'EOP Süreç Adım Tanımı',
                'verbose_name_plural': 'EOP Süreç Adım Tanımları',
                'ordering': ['adim_no'],
            },
        ),
        migrations.CreateModel(
            name='EOPSureci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='EOP Takip Kodu (EOP)')),
                ('urun_kodu', models.CharField(max_length=100, verbose_name='Sonlandırılacak Ürün / Parça Kodu')),
                ('urun_adi', models.CharField(max_length=200, verbose_name='Ürün Adı / Proje Tanımı')),
                ('musteri_adi', models.CharField(max_length=150, verbose_name='Müşteri / Firma Adı')),
                ('urun_grubu', models.CharField(choices=[('Metal Parca & Sac', 'Metal Parça & Sac Şekillendirme'), ('Kondenser & Sogutma', 'Kondenser & Soğutma'), ('Kablo Grubu', 'Kablo Grubu & Demetleri'), ('Kalıp & Fikstür', 'Kalıp, Fikstür & Aparat'), ('Montaj ve Kaynak', 'Montaj ve Kaynak'), ('Plastik Enjeksiyon', 'Plastik Enjeksiyon'), ('Batarya & EV Bilesenleri', 'Batarya & EV Bileşenleri'), ('Genel / Diger', 'Genel / Diğer')], default='Kondenser', max_length=100, verbose_name='Ürün Grubu')),
                ('ilgili_fabrika', models.CharField(choices=[('Teleset 1 (Manisa)', 'Teleset 1 (Manisa)'), ('Teleset 2 (Manisa)', 'Teleset 2 (Manisa)'), ('Teleset 3 (Kocaeli)', 'Teleset 3 (Kocaeli)'), ('Teleset Otomotiv', 'Teleset Otomotiv'), ('Teleset Global', 'Teleset Global')], default='Teleset 1 (Manisa)', max_length=100, verbose_name='İlgili Fabrika')),
                ('eop_bildirim_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='EOP Bildirim Tarihi')),
                ('seri_uretim_bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Seri Üretim Bitiş Tarihi')),
                ('yedek_parca_servis_suresi_yil', models.PositiveSmallIntegerField(default=10, verbose_name='Yedek Parça Servis Yükümlülüğü (Yıl)')),
                ('sorumlu_proje_sorumlusu', models.CharField(default='Buse Nur Baltacıoğlu', max_length=100, verbose_name='Proje Sorumlusu (R)')),
                ('sorumlu_fabrika_muduru', models.CharField(default='Serdar Acar', max_length=100, verbose_name='Fabrika Müdürü (A)')),
                ('sorumlu_satis_analiz', models.CharField(default='Hakan Yılmaz', max_length=100, verbose_name='Satış-Analiz Sorumlusu (C)')),
                ('sorumlu_planlama', models.CharField(default='Canan Kaya', max_length=100, verbose_name='Planlama Sorumlusu (C)')),
                ('sorumlu_uretim', models.CharField(default='Murat Çelik', max_length=100, verbose_name='Üretim Sorumlusu (C)')),
                ('durum', models.CharField(choices=[('DEVAM_EDIYOR', 'Devam Ediyor'), ('STOK_TASFIYESINDE', 'Stok Tasfiyesi / Değerlendirme Aşamasında'), ('VARLIK_DEVRI_TAMAMLANDI', 'Üretim Varlıkları Tasfiyesi Tamamlandı'), ('BASARIYLA_KAPATILDI', 'Başarıyla Tamamlandı & Kapatıldı'), ('IPTAL_EDILDI', 'İptal Edildi')], default='DEVAM_EDIYOR', max_length=40, verbose_name='Süreç Durumu')),
                ('guncel_adim_no', models.PositiveSmallIntegerField(default=1, verbose_name='Güncel Adım No')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='EOP Açıklaması / Müşteri Bildirim Notları')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('musteri_karti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eop_surecleri', to='crm_takip.musterikarti', verbose_name='Müşteri Portföy Kartı')),
            ],
            options={
                'verbose_name': 'Ürün Seri Üretim Sonlandırma (EOP) Süreci',
                'verbose_name_plural': 'Ürün Seri Üretim Sonlandırma (EOP) Süreçleri',
                'ordering': ['-guncelleme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='EOPGecmisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(max_length=255, verbose_name='Yapılan İşlem')),
                ('detay', models.TextField(blank=True, null=True, verbose_name='İşlem Detayı')),
                ('yapan', models.CharField(default='Sistem', max_length=100, verbose_name='İşlemi Yapan')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('surec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarihce_kayitlari', to='crm_takip.eopsureci', verbose_name='EOP Süreci')),
            ],
            options={
                'verbose_name': 'EOP Geçmiş Logu',
                'verbose_name_plural': 'EOP Geçmiş Logları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='EOPAdimKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('DEVAM_EDIYOR', 'Devam Ediyor / Aktif'), ('TAMAMLANDI', 'Tamamlandı (Onaylandı)'), ('PAS_GECILDI', 'Pas Geçildi / Muaf')], default='BEKLIYOR', max_length=30, verbose_name='Durum')),
                ('tamamlayan', models.CharField(blank=True, max_length=100, null=True, verbose_name='İşlemi Yapan')),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('karar_sonucu', models.CharField(blank=True, max_length=150, null=True, verbose_name='Verilen Karar / Mutabakat')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Adım Notları / Değerlendirme / Çıktı')),
                ('dokuman_referansi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Doküman Linki / Form No')),
                ('adim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_takip.eopsurecadimtanimi', verbose_name='Süreç Adımı')),
                ('surec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adim_kayitlari', to='crm_takip.eopsureci', verbose_name='EOP Süreci')),
            ],
            options={
                'verbose_name': 'EOP Adım Kaydı',
                'verbose_name_plural': 'EOP Adım Kayıtları',
                'ordering': ['adim__adim_no'],
                'unique_together': {('surec', 'adim')},
            },
        ),
    ]
