# Generated by Django 6.0.4 on 2026-09-11 14:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0012_eopsurecadimtanimi_eopsureci_eopgecmislog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaaliyetKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('SEYAHAT', 'Müşteri / İş Seyahati'), ('TOPLANTI', 'Müşteri / İç Toplantı'), ('FUAR', 'Fuar & Sektörel Etkinlik'), ('DESTEK', 'Destek & Aksiyon Talebi')], default='TOPLANTI', max_length=20, verbose_name='Faaliyet / Talep Türü')),
                ('baslik', models.CharField(max_length=255, verbose_name='Faaliyet / Talep Başlığı')),
                ('sorumlu_kisi', models.CharField(default='Buse Nur Baltacıoğlu', max_length=120, verbose_name='Sorumlu Personel')),
                ('musteri_adi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Müşteri / Firma Adı')),
                ('lokasyon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lokasyon / Yer / Kanal')),
                ('baslangic_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Bitiş Tarihi')),
                ('saat_araligi', models.CharField(blank=True, default='09:00 - 10:30', max_length=60, null=True, verbose_name='Saat / Zaman Dilimi')),
                ('oncelik', models.CharField(choices=[('DUSUK', 'Düşük'), ('ORTA', 'Orta'), ('YUKSEK', 'Yüksek'), ('KRITIK', 'Kritik / Acil')], default='ORTA', max_length=20, verbose_name='Öncelik Seviyesi')),
                ('durum', models.CharField(choices=[('PLANLANDI', 'Planlandı'), ('DEVAM_EDIYOR', 'Devam Ediyor / Hazırlık'), ('ONAYDA', 'Yönetici Onayında'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL', 'İptal Edildi')], default='PLANLANDI', max_length=20, verbose_name='Durum')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama, Gündem & Notlar')),
                ('tahmini_butce', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Tahmini Bütçe / Masraf')),
                ('olusturan', models.CharField(default='Buse Nur Baltacıoğlu', max_length=100, verbose_name='Oluşturan')),
                ('olusturuldu_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncellendi_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('musteri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faaliyetler', to='crm_takip.musterikarti', verbose_name='İlişkili Müşteri')),
            ],
            options={
                'verbose_name': 'Faaliyet / Talep Kaydı',
                'verbose_name_plural': 'Faaliyet & Talep Kayıtları',
                'ordering': ['baslangic_tarihi', 'durum'],
            },
        ),
    ]
