# Generated by Django 6.0.4 on 2026-09-14 07:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0013_faaliyetkaydi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musterikarti',
            name='churn_riski',
            field=models.CharField(default='0.05 (Düşük Risk)', max_length=50, verbose_name='Müşteri Kayıp Riski'),
        ),
        migrations.AlterField(
            model_name='musterikarti',
            name='kam_kalite_lideri',
            field=models.CharField(default='Mehmet YILMAZ (Kalite Güvence Md.)', max_length=100, verbose_name='KAM Kalite Lideri'),
        ),
        migrations.AlterField(
            model_name='musterikarti',
            name='kam_muhendislik_lideri',
            field=models.CharField(default='Ahmet AK (Kalıp & Projeci Md.)', max_length=100, verbose_name='KAM Projeci Lideri'),
        ),
        migrations.AlterField(
            model_name='musterikarti',
            name='kam_satis_lideri',
            field=models.CharField(default='Buse Nur BALTACIOĞLU', max_length=100, verbose_name='KAM Satış Lideri'),
        ),
        migrations.AlterField(
            model_name='musterikarti',
            name='sozlesme_durumu',
            field=models.CharField(default='STG-TL-001 (Aktif)', max_length=150, verbose_name='Sözleşme & Onay Durumu'),
        ),
        migrations.AlterField(
            model_name='musterikarti',
            name='strateji',
            field=models.CharField(choices=[('Protect', 'Protect (İlişkiyi Koru & Derinleştir)'), ('Grow', 'Grow (Cüzdan Payını ve Hacmi Büyüt)'), ('Harvest', 'Harvest (Kârlılık Odaklı Yönet)'), ('Re-engineer', 'Re-engineer (Süreç & Maliyet İyileştirme)'), ('Start', 'Start (Yeni Başlangıç / Geliştirme)')], default='Protect', max_length=30, verbose_name='CPM Stratejisi'),
        ),
        migrations.CreateModel(
            name='MusteriTesisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tesis_adi', models.CharField(max_length=150, verbose_name='Tesis / Fabrika Adı')),
                ('lokasyon', models.CharField(max_length=150, verbose_name='Şehir / Ülke')),
                ('kod', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tesis Kodu')),
                ('clv_m', models.CharField(default='45.8 M€', max_length=50, verbose_name='Yaşam Boyu Değer (CLV)')),
                ('churn_skoru', models.CharField(default='0.05', max_length=50, verbose_name='Terk (Churn) Skoru')),
                ('churn_durumu', models.CharField(default='Düşük Risk', max_length=50, verbose_name='Churn Durumu')),
                ('yillik_ciro_str', models.CharField(default='€ 12.18M', max_length=50, verbose_name='Yıllık Ciro')),
                ('ciro_alt_bilgi', models.CharField(default='1.284 Stok Kodu', max_length=100, verbose_name='Ciro Alt Bilgi')),
                ('cuzdan_payi_yuzde', models.PositiveSmallIntegerField(default=58, verbose_name='Cüzdan Payı %')),
                ('cuzdan_alt_bilgi', models.CharField(default='Sac & Kablo Grubu', max_length=100, verbose_name='Cüzdan Alt Bilgi')),
                ('destek_sayisi', models.PositiveSmallIntegerField(default=9, verbose_name='Destek / Talep Sayısı')),
                ('npi_proje_sayisi', models.PositiveSmallIntegerField(default=28, verbose_name='NPI Proje Sayısı')),
                ('teklif_sayisi', models.PositiveSmallIntegerField(default=9, verbose_name='Teklif (SAT) Sayısı')),
                ('sevkiyat_sayisi', models.PositiveSmallIntegerField(default=9, verbose_name='Sevkiyat Sayısı')),
                ('kam_satis_lideri', models.CharField(default='Buse Nur BALTACIOĞLU', max_length=100, verbose_name='Satış Lead')),
                ('kam_muhendislik_lideri', models.CharField(default='Ahmet AK (Kalıp & Projeci Md.)', max_length=100, verbose_name='Kalıp/Projeci Lead')),
                ('kam_kalite_lideri', models.CharField(default='Mehmet YILMAZ (Kalite Mühendisi)', max_length=100, verbose_name='Kalite Lead')),
                ('yetkili_adi', models.CharField(default='Klaus Schmidt', max_length=150, verbose_name='Müşteri Yetkilisi')),
                ('yetkili_unvan', models.CharField(default='Global Satınalma Direktörü', max_length=150, verbose_name='Yetkili Unvanı')),
                ('yetkili_email', models.CharField(default='klaus.schmidt@bsh.com', max_length=150, verbose_name='Yetkili E-Posta')),
                ('yetkili_telefon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yetkili Telefon')),
                ('son_etkilesim', models.CharField(default='Dün 14:30 - Yeni SIMPAC 400T Kalıp İncelemesi', max_length=200, verbose_name='Son Etkileşim')),
                ('sira', models.PositiveSmallIntegerField(default=1, verbose_name='Sıralama')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tesisler', to='crm_takip.musterikarti', verbose_name='Müşteri Grubu')),
            ],
            options={
                'verbose_name': 'Müşteri Tesisi',
                'verbose_name_plural': 'Müşteri Tesisleri',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MusteriEtkilesimZamanTuneli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(default='SAT-EK-005', max_length=50, verbose_name='Süreç / Form Kodu')),
                ('baslik', models.CharField(max_length=200, verbose_name='Aktivite Başlığı')),
                ('aciklama', models.TextField(verbose_name='Açıklama / Detay')),
                ('sorumlu', models.CharField(default='Buse Nur BALTACIOĞLU', max_length=100, verbose_name='Sorumlu Kişi')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('donem_ay_yil', models.CharField(default='EYLÜL 2026', max_length=50, verbose_name='Dönem Başlığı')),
                ('ikon', models.CharField(default='bi-file-earmark-text-fill', max_length=50, verbose_name='Bootstrap İkonu')),
                ('ikon_bg', models.CharField(default='bg-warning', max_length=50, verbose_name='İkon Arka Planı')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etkilesimler', to='crm_takip.musterikarti', verbose_name='Müşteri')),
                ('tesis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etkilesimler', to='crm_takip.musteritesisi', verbose_name='İlgili Tesis')),
            ],
            options={
                'verbose_name': 'Müşteri Etkileşim Kaydı',
                'verbose_name_plural': 'Müşteri Etkileşim Kayıtları',
                'ordering': ['-tarih', '-id'],
            },
        ),
    ]
