# Generated by Django 6.0.4 on 2026-09-14 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0014_alter_musterikarti_churn_riski_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaProje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_kodu', models.CharField(max_length=50, unique=True, verbose_name='Proje Kodu')),
                ('proje_adi', models.CharField(max_length=200, verbose_name='Proje Başlığı')),
                ('parca_kodu', models.CharField(max_length=100, verbose_name='Parça / Kalıp Kodu')),
                ('fabrika', models.CharField(choices=[('Preshane & Kalıphane', 'Preshane & Kalıphane'), ('Teleset 1 (Manisa)', 'Teleset 1 (Manisa)'), ('Teleset 2 (Manisa)', 'Teleset 2 (Manisa)'), ('Teleset 3 (Kocaeli)', 'Teleset 3 (Kocaeli)'), ('Teleset Otomotiv', 'Teleset Otomotiv'), ('Teleset Global', 'Teleset Global')], default='Preshane & Kalıphane', max_length=100, verbose_name='Fabrika / Bölüm')),
                ('sorumlu_lider', models.CharField(default='Buse Nur Baltacıoğlu', max_length=120, verbose_name='Proje Lideri')),
                ('hedef_sop_tarihi', models.DateField(blank=True, null=True, verbose_name='Hedef Seri Üretim Tarihi')),
                ('genel_ilerleme_yuzdesi', models.IntegerField(default=50, verbose_name='Genel İlerleme %')),
                ('aktif_surec_no', models.IntegerField(default=6, verbose_name='Aktif Süreç No (1-8)')),
                ('aktif_surec_adi', models.CharField(default='Yeni Ürün Devreye Alma Süreci', max_length=120, verbose_name='Aktif Süreç Adı')),
                ('aktif_adim_no', models.IntegerField(default=18, verbose_name='Aktif Adım No')),
                ('aktif_adim_basligi', models.CharField(default='T0 Kalıp Denemesi ve İlk Numune Basımı', max_length=255, verbose_name='Aktif Adım Başlığı')),
                ('aktif_rol', models.CharField(default='Projeci / Kalıp', max_length=100, verbose_name='Aktif Rol Sorumlusu')),
                ('aktif_durum_aciklamasi', models.CharField(default='Kalıp denemesi tamamlandı, CMM boyutsal ölçüm raporu bekleniyor.', max_length=255, verbose_name='Durum Özeti / Not')),
                ('durum', models.CharField(default='Devam Ediyor', max_length=50, verbose_name='Proje Genel Durumu')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('eop_sureci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bagli_ana_projeler', to='crm_takip.eopsureci')),
                ('muhendislik_degisikligi_sureci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bagli_ana_projeler', to='crm_takip.muhendislikdegisikligisureci')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ana_projeler', to='crm_takip.musterikarti', verbose_name='Cari / Müşteri')),
                ('musteri_iliskileri_sureci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bagli_ana_projeler', to='crm_takip.musteriiliskilerisureci')),
                ('pazarlama_sureci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bagli_ana_projeler', to='crm_takip.pazarlamaprojesi')),
                ('prototip_sureci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bagli_ana_projeler', to='crm_takip.prototipsureci')),
                ('sozlesme_sureci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bagli_ana_projeler', to='crm_takip.sozlesmesureci')),
                ('tesis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ana_projeler', to='crm_takip.musteritesisi', verbose_name='Müşteri Tesisi / Lokasyonu')),
                ('urun_teklif_sureci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bagli_ana_projeler', to='crm_takip.urunteklifsureci')),
                ('yeni_urun_sureci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bagli_ana_projeler', to='crm_takip.yeniurundevreyealmasureci')),
            ],
            options={
                'verbose_name': 'Uçtan Uca Ana Proje',
                'verbose_name_plural': 'Uçtan Uca Ana Projeler',
                'ordering': ['proje_kodu'],
            },
        ),
    ]
