# Generated by Django 6.0.4 on 2026-09-14 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0015_anaproje'),
    ]

    operations = [
        migrations.AddField(
            model_name='anaproje',
            name='dijital_iplik_senkronize_mi',
            field=models.BooleanField(default=True, verbose_name='Teklif & APQP Veri Senkronizasyonu Aktif mi?'),
        ),
        migrations.AddField(
            model_name='anaproje',
            name='hammadde_cinsi',
            field=models.CharField(blank=True, default='DC01 Galvaniz Sac / 1.20mm', max_length=120, verbose_name='Hammadde / Spesifikasyon'),
        ),
        migrations.AddField(
            model_name='anaproje',
            name='hedef_butce',
            field=models.DecimalField(blank=True, decimal_places=2, default=125000.0, max_digits=14, null=True, verbose_name='Hedef Proje / Teklif Bütçesi (EUR)'),
        ),
        migrations.AddField(
            model_name='anaproje',
            name='kalip_goz_sayisi',
            field=models.IntegerField(default=4, verbose_name='Kalıp Göz Sayısı'),
        ),
        migrations.AddField(
            model_name='anaproje',
            name='yillik_hacim_adet',
            field=models.IntegerField(default=50000, verbose_name='Yıllık Tahmini Hacim (Adet)'),
        ),
        migrations.AddField(
            model_name='muhendislikdegisikligisureci',
            name='ana_proje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_iterasyonlari', to='crm_takip.anaproje', verbose_name='Bağlı Ana Proje'),
        ),
        migrations.AddField(
            model_name='prototipsureci',
            name='ana_proje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prototip_iterasyonlari', to='crm_takip.anaproje', verbose_name='Bağlı Ana Proje'),
        ),
    ]
