# Generated by Django 6.0.4 on 2026-09-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0016_anaproje_dijital_iplik_senkronize_mi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemKodSayaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surec_tipi', models.CharField(max_length=20, verbose_name='Süreç Tipi (PRJ, TEK, ECO vb.)')),
                ('yil', models.IntegerField(verbose_name='Yıl')),
                ('son_sira_no', models.IntegerField(default=100, verbose_name='Son Verilen Sıra Numarası')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sistem Kod Sayacı',
                'verbose_name_plural': 'Sistem Kod Sayaçları',
                'unique_together': {('surec_tipi', 'yil')},
            },
        ),
    ]
