# Generated by Django 6.0.4 on 2026-09-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0017_sistemkodsayaci'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='ana_kaldirac',
            field=models.TextField(blank=True, null=True, verbose_name='1 Ana Kaldıraç'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='ana_risk',
            field=models.TextField(blank=True, null=True, verbose_name='1 Ana Risk'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='hedef_6p_fiyat',
            field=models.TextField(blank=True, null=True, verbose_name='3.2 Fiyat (Price) Hedefleri'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='hedef_6p_insan',
            field=models.TextField(blank=True, null=True, verbose_name='3.5 İnsan (People) Hedefleri'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='hedef_6p_promosyon',
            field=models.TextField(blank=True, null=True, verbose_name='3.4 Promosyon (Promotion) Hedefleri'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='hedef_6p_surec',
            field=models.TextField(blank=True, null=True, verbose_name='3.6 Süreç (Process) Hedefleri'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='hedef_6p_urun',
            field=models.TextField(blank=True, null=True, verbose_name='3.1 Ürün (Product) Hedefleri'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='hedef_6p_yer_dagitim',
            field=models.TextField(blank=True, null=True, verbose_name='3.3 Yer (Place) / Dağıtım Hedefleri'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='hedef_fuarlar',
            field=models.TextField(blank=True, null=True, verbose_name='Hedef Sektörel Fuarlar & Etkinlikler'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='hizli_kazanim',
            field=models.TextField(blank=True, null=True, verbose_name='1 Hızlı Kazanım'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='kritik_basari_faktorleri',
            field=models.TextField(blank=True, null=True, verbose_name='Teleset İçin 3 Kritik Başarı Faktörü'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='oncelikli_eylemler',
            field=models.TextField(blank=True, null=True, verbose_name='4. Öncelikli Eylemler (2025–2028)'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='sektorel_yayinlar',
            field=models.TextField(blank=True, null=True, verbose_name='Sektörel Yayınlar & Medya'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='stratejik_bahis',
            field=models.TextField(blank=True, null=True, verbose_name='Stratejik Bahis (2025–2028)'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='swot_firsatlar',
            field=models.TextField(blank=True, null=True, verbose_name='Fırsatları Değerlendirme Stratejileri'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='swot_guclu_yonler',
            field=models.TextField(blank=True, null=True, verbose_name='Güçlü Yönlerden Yararlanma Stratejileri'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='swot_tehditler',
            field=models.TextField(blank=True, null=True, verbose_name='Tehditleri Azaltma Stratejileri'),
        ),
        migrations.AddField(
            model_name='hedefpazarkanvas',
            name='swot_zayif_yonler',
            field=models.TextField(blank=True, null=True, verbose_name='Zayıf Yönleri Minimize Etme Stratejileri'),
        ),
        migrations.AlterField(
            model_name='anaproje',
            name='fabrika',
            field=models.CharField(choices=[('PRESHANE', 'PRESHANE'), ('KALIPHANE', 'KALIPHANE'), ('CERKEZKOY', 'CERKEZKOY'), ('KABLOGR', 'KABLOGR'), ('KONDANSER', 'KONDANSER'), ('MANISA ORTAK', 'MANISA ORTAK')], default='PRESHANE', max_length=100, verbose_name='Ana Departman / Bölüm'),
        ),
        migrations.AlterField(
            model_name='eopsureci',
            name='ilgili_fabrika',
            field=models.CharField(choices=[('PRESHANE', 'PRESHANE'), ('KALIPHANE', 'KALIPHANE'), ('CERKEZKOY', 'CERKEZKOY'), ('KABLOGR', 'KABLOGR'), ('KONDANSER', 'KONDANSER'), ('MANISA ORTAK', 'MANISA ORTAK')], default='PRESHANE', max_length=100, verbose_name='İlgili Fabrika'),
        ),
        migrations.AlterField(
            model_name='eopsureci',
            name='sorumlu_fabrika_muduru',
            field=models.CharField(default='ONUR TUNCER', max_length=100, verbose_name='Fabrika Müdürü (A)'),
        ),
        migrations.AlterField(
            model_name='eopsureci',
            name='sorumlu_planlama',
            field=models.CharField(default='MUHARREM FURKAN TARHAN', max_length=100, verbose_name='Planlama Sorumlusu (C)'),
        ),
        migrations.AlterField(
            model_name='eopsureci',
            name='sorumlu_proje_sorumlusu',
            field=models.CharField(default='BUSE NUR BALTACIOĞLU', max_length=100, verbose_name='Proje Sorumlusu (R)'),
        ),
        migrations.AlterField(
            model_name='eopsureci',
            name='sorumlu_satis_analiz',
            field=models.CharField(default='METİN YAVAŞ', max_length=100, verbose_name='Satış-Analiz Sorumlusu (C)'),
        ),
        migrations.AlterField(
            model_name='eopsureci',
            name='sorumlu_uretim',
            field=models.CharField(default='YİĞİT EFE BİLİR', max_length=100, verbose_name='Üretim Sorumlusu (C)'),
        ),
        migrations.AlterField(
            model_name='muhendislikdegisikligisureci',
            name='ilgili_fabrika',
            field=models.CharField(choices=[('PRESHANE', 'PRESHANE'), ('KALIPHANE', 'KALIPHANE'), ('CERKEZKOY', 'CERKEZKOY'), ('KABLOGR', 'KABLOGR'), ('KONDANSER', 'KONDANSER'), ('MANISA ORTAK', 'MANISA ORTAK')], default='PRESHANE', max_length=100, verbose_name='İlgili Fabrika'),
        ),
        migrations.AlterField(
            model_name='muhendislikdegisikligisureci',
            name='sorumlu_fabrika_muduru',
            field=models.CharField(default='ONUR TUNCER', max_length=100, verbose_name='Fabrika Müdürü (A)'),
        ),
        migrations.AlterField(
            model_name='muhendislikdegisikligisureci',
            name='sorumlu_kalite',
            field=models.CharField(default='MUHARREM FURKAN TARHAN', max_length=100, verbose_name='Kalite Sorumlusu (C)'),
        ),
        migrations.AlterField(
            model_name='muhendislikdegisikligisureci',
            name='sorumlu_proje_sorumlusu',
            field=models.CharField(default='BUSE NUR BALTACIOĞLU', max_length=100, verbose_name='Proje Sorumlusu (R)'),
        ),
        migrations.AlterField(
            model_name='muhendislikdegisikligisureci',
            name='sorumlu_satis_analiz',
            field=models.CharField(default='METİN YAVAŞ', max_length=100, verbose_name='Satış-Analiz Sorumlusu (C)'),
        ),
        migrations.AlterField(
            model_name='musteriiliskilerisureci',
            name='ilgili_fabrika',
            field=models.CharField(choices=[('PRESHANE', 'PRESHANE'), ('KALIPHANE', 'KALIPHANE'), ('CERKEZKOY', 'CERKEZKOY'), ('KABLOGR', 'KABLOGR'), ('KONDANSER', 'KONDANSER'), ('MANISA ORTAK', 'MANISA ORTAK')], default='PRESHANE', max_length=100, verbose_name='İlgili Fabrika'),
        ),
        migrations.AlterField(
            model_name='musteriiliskilerisureci',
            name='sorumlu_eys',
            field=models.CharField(default='BUSE NUR BALTACIOĞLU', max_length=100, verbose_name='EYS Sorumlusu'),
        ),
        migrations.AlterField(
            model_name='musteriiliskilerisureci',
            name='sorumlu_surec_sahibi',
            field=models.CharField(default='ONUR TUNCER', max_length=100, verbose_name='Süreç Sahibi / İyileştirme Ekibi'),
        ),
        migrations.AlterField(
            model_name='musteritesisi',
            name='kam_kalite_lideri',
            field=models.CharField(default='METİN YAVAŞ (Bakım & Kalite Şefi)', max_length=100, verbose_name='Kalite Lead'),
        ),
        migrations.AlterField(
            model_name='musteritesisi',
            name='kam_muhendislik_lideri',
            field=models.CharField(default='YİĞİT EFE BİLİR (İş Çözümleri Mühendisi)', max_length=100, verbose_name='Kalıp/Projeci Lead'),
        ),
        migrations.AlterField(
            model_name='musteritesisi',
            name='kam_satis_lideri',
            field=models.CharField(default='BUSE NUR BALTACIOĞLU (İş Geliştirme)', max_length=100, verbose_name='Satış Lead'),
        ),
        migrations.AlterField(
            model_name='pazarlamaprojesi',
            name='ilgili_fabrika',
            field=models.CharField(choices=[('PRESHANE', 'PRESHANE'), ('KALIPHANE', 'KALIPHANE'), ('CERKEZKOY', 'CERKEZKOY'), ('KABLOGR', 'KABLOGR'), ('KONDANSER', 'KONDANSER'), ('MANISA ORTAK', 'MANISA ORTAK')], default='PRESHANE', max_length=100, verbose_name='İlgili Fabrika / Ana Departman'),
        ),
        migrations.AlterField(
            model_name='pazarlamaprojesi',
            name='sorumlu_pazarlama_uzmani',
            field=models.CharField(default='BUSE NUR BALTACIOĞLU', max_length=100, verbose_name='Pazarlama Uzmanı (R)'),
        ),
        migrations.AlterField(
            model_name='pazarlamaprojesi',
            name='sorumlu_satis_muduru',
            field=models.CharField(default='YİĞİT EFE BİLİR', max_length=100, verbose_name='Satış & Pazarlama Müdürü (A)'),
        ),
        migrations.AlterField(
            model_name='prototipsureci',
            name='ilgili_fabrika',
            field=models.CharField(choices=[('PRESHANE', 'PRESHANE'), ('KALIPHANE', 'KALIPHANE'), ('CERKEZKOY', 'CERKEZKOY'), ('KABLOGR', 'KABLOGR'), ('KONDANSER', 'KONDANSER'), ('MANISA ORTAK', 'MANISA ORTAK')], default='PRESHANE', max_length=100, verbose_name='İlgili Fabrika'),
        ),
        migrations.AlterField(
            model_name='prototipsureci',
            name='sorumlu_fabrika_muduru',
            field=models.CharField(default='ONUR TUNCER', max_length=100, verbose_name='Fabrika Müdürü (A)'),
        ),
        migrations.AlterField(
            model_name='prototipsureci',
            name='sorumlu_kalite',
            field=models.CharField(default='MUHARREM FURKAN TARHAN', max_length=100, verbose_name='Kalite Sorumlusu (C)'),
        ),
        migrations.AlterField(
            model_name='prototipsureci',
            name='sorumlu_proje_sorumlusu',
            field=models.CharField(default='BUSE NUR BALTACIOĞLU', max_length=100, verbose_name='Proje Sorumlusu (R)'),
        ),
        migrations.AlterField(
            model_name='prototipsureci',
            name='sorumlu_satis_analiz',
            field=models.CharField(default='METİN YAVAŞ', max_length=100, verbose_name='Satış-Analiz Sorumlusu (C)'),
        ),
        migrations.AlterField(
            model_name='sozlesmesureci',
            name='ilgili_fabrika',
            field=models.CharField(choices=[('PRESHANE', 'PRESHANE'), ('KALIPHANE', 'KALIPHANE'), ('CERKEZKOY', 'CERKEZKOY'), ('KABLOGR', 'KABLOGR'), ('KONDANSER', 'KONDANSER'), ('MANISA ORTAK', 'MANISA ORTAK')], default='PRESHANE', max_length=100, verbose_name='İlgili Fabrika'),
        ),
        migrations.AlterField(
            model_name='sozlesmesureci',
            name='sorumlu_fabrika_muduru',
            field=models.CharField(default='MUHARREM FURKAN TARHAN', max_length=100, verbose_name='Fabrika Müdürü'),
        ),
        migrations.AlterField(
            model_name='sozlesmesureci',
            name='sorumlu_hukuk',
            field=models.CharField(default='Hukuk Müşaviri', max_length=100, verbose_name='Şirket Hukuk Müşaviri / Avukat'),
        ),
        migrations.AlterField(
            model_name='sozlesmesureci',
            name='sorumlu_satis_uzmani',
            field=models.CharField(default='BUSE NUR BALTACIOĞLU', max_length=100, verbose_name='Satış Uzmanı'),
        ),
        migrations.AlterField(
            model_name='sozlesmesureci',
            name='sorumlu_satis_yoneticisi',
            field=models.CharField(default='ONUR TUNCER', max_length=100, verbose_name='Satış Yöneticisi'),
        ),
        migrations.AlterField(
            model_name='urunteklifsureci',
            name='ilgili_fabrika',
            field=models.CharField(choices=[('PRESHANE', 'PRESHANE'), ('KALIPHANE', 'KALIPHANE'), ('CERKEZKOY', 'CERKEZKOY'), ('KABLOGR', 'KABLOGR'), ('KONDANSER', 'KONDANSER'), ('MANISA ORTAK', 'MANISA ORTAK')], default='PRESHANE', max_length=100, verbose_name='İlgili Fabrika'),
        ),
        migrations.AlterField(
            model_name='urunteklifsureci',
            name='sorumlu_satis_analiz_uzmani',
            field=models.CharField(default='METİN YAVAŞ', max_length=100, verbose_name='Satış Analiz Uzmanı'),
        ),
        migrations.AlterField(
            model_name='urunteklifsureci',
            name='sorumlu_satis_uzmani',
            field=models.CharField(default='BUSE NUR BALTACIOĞLU', max_length=100, verbose_name='Satış Uzmanı'),
        ),
        migrations.AlterField(
            model_name='urunteklifsureci',
            name='sorumlu_satis_yoneticisi',
            field=models.CharField(default='ONUR TUNCER', max_length=100, verbose_name='Satış Yöneticisi'),
        ),
        migrations.AlterField(
            model_name='yeniurundevreyealmasureci',
            name='ilgili_fabrika',
            field=models.CharField(choices=[('PRESHANE', 'PRESHANE'), ('KALIPHANE', 'KALIPHANE'), ('CERKEZKOY', 'CERKEZKOY'), ('KABLOGR', 'KABLOGR'), ('KONDANSER', 'KONDANSER'), ('MANISA ORTAK', 'MANISA ORTAK')], default='PRESHANE', max_length=100, verbose_name='Üretim Fabrikası / Ana Departman'),
        ),
        migrations.AlterField(
            model_name='yeniurundevreyealmasureci',
            name='sorumlu_fabrika_muduru',
            field=models.CharField(default='ONUR TUNCER', max_length=100, verbose_name='Fabrika Müdürü'),
        ),
        migrations.AlterField(
            model_name='yeniurundevreyealmasureci',
            name='sorumlu_kalite',
            field=models.CharField(default='METİN YAVAŞ', max_length=100, verbose_name='Kalite Sorumlusu'),
        ),
        migrations.AlterField(
            model_name='yeniurundevreyealmasureci',
            name='sorumlu_proje_lideri',
            field=models.CharField(default='BUSE NUR BALTACIOĞLU', max_length=100, verbose_name='Proje Sorumlusu'),
        ),
        migrations.AlterField(
            model_name='yeniurundevreyealmasureci',
            name='sorumlu_satis_analiz',
            field=models.CharField(default='MUHARREM FURKAN TARHAN', max_length=100, verbose_name='Satış-Analiz Sorumlusu'),
        ),
    ]
