# Generated by Django 6.0.4 on 2026-09-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0018_hedefpazarkanvas_ana_kaldirac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anaproje',
            name='aciklama_notu',
            field=models.TextField(blank=True, default='', verbose_name='Açıklama / Durum Notu'),
        ),
        migrations.AddField(
            model_name='anaproje',
            name='bolum',
            field=models.CharField(default='Kalıphane', max_length=100, verbose_name='Bölüm / Departman'),
        ),
        migrations.AddField(
            model_name='anaproje',
            name='parca_adi',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Parça Adı'),
        ),
        migrations.AddField(
            model_name='anaproje',
            name='proje_baslangic_tarihi_str',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Proje Başlangıç Tarihi'),
        ),
        migrations.AddField(
            model_name='anaproje',
            name='proje_bitis_tarihi_str',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Proje Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='anaproje',
            name='proje_hedef_tarihi_str',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Proje Hedef Tarihi'),
        ),
        migrations.AddField(
            model_name='anaproje',
            name='proje_onay_tarihi_str',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Proje Onay Tarihi'),
        ),
        migrations.AddField(
            model_name='anaproje',
            name='urun_grubu',
            field=models.CharField(default='Kurutucu', max_length=100, verbose_name='Ürün Grubu'),
        ),
        migrations.AddField(
            model_name='anaproje',
            name='yillik_frc_miktar',
            field=models.BigIntegerField(default=0, verbose_name='Yıllık FRC Miktar (Adet)'),
        ),
        migrations.AlterField(
            model_name='anaproje',
            name='parca_kodu',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Parça / Kalıp Kodu'),
        ),
        migrations.AlterField(
            model_name='eopsureci',
            name='urun_grubu',
            field=models.CharField(choices=[('Metal Parca & Sac', 'Metal Parça & Sac Şekillendirme'), ('Kondanser & Sogutma', 'Kondanser & Soğutma'), ('Kondenser & Sogutma', 'Kondanser & Soğutma (Eski)'), ('Kablo Grubu', 'Kablo Grubu & Demetleri'), ('Kalıp & Fikstür', 'Kalıp, Fikstür & Aparat'), ('Montaj ve Kaynak', 'Montaj ve Kaynak'), ('Plastik Enjeksiyon', 'Plastik Enjeksiyon'), ('Batarya & EV Bilesenleri', 'Batarya & EV Bileşenleri'), ('Genel / Diger', 'Genel / Diğer')], default='Kondanser & Sogutma', max_length=100, verbose_name='Ürün Grubu'),
        ),
        migrations.AlterField(
            model_name='hedefpazarkanvas',
            name='hedef_urunler',
            field=models.CharField(default='Kondanser, Kablo Grubu, Metal Parça, Kalıp', max_length=255, verbose_name='Hedef Ürün Grupları'),
        ),
        migrations.AlterField(
            model_name='muhendislikdegisikligisureci',
            name='urun_grubu',
            field=models.CharField(choices=[('Metal Parca & Sac', 'Metal Parça & Sac Şekillendirme'), ('Kondanser & Sogutma', 'Kondanser & Soğutma'), ('Kondenser & Sogutma', 'Kondanser & Soğutma (Eski)'), ('Kablo Grubu', 'Kablo Grubu & Demetleri'), ('Kalıp & Fikstür', 'Kalıp, Fikstür & Aparat'), ('Montaj ve Kaynak', 'Montaj ve Kaynak'), ('Plastik Enjeksiyon', 'Plastik Enjeksiyon'), ('Batarya & EV Bilesenleri', 'Batarya & EV Bileşenleri'), ('Genel / Diger', 'Genel / Diğer')], default='Metal Parca & Sac', max_length=100, verbose_name='Ürün Grubu'),
        ),
        migrations.AlterField(
            model_name='pazarlamaprojesi',
            name='urun_grubu',
            field=models.CharField(choices=[('Metal Parca & Sac', 'Metal Parça & Sac Şekillendirme'), ('Kondanser & Sogutma', 'Kondanser & Soğutma'), ('Kondenser & Sogutma', 'Kondanser & Soğutma (Eski)'), ('Kablo Grubu', 'Kablo Grubu & Demetleri'), ('Kalıp & Fikstür', 'Kalıp, Fikstür & Aparat'), ('Montaj ve Kaynak', 'Montaj ve Kaynak'), ('Plastik Enjeksiyon', 'Plastik Enjeksiyon'), ('Batarya & EV Bilesenleri', 'Batarya & EV Bileşenleri'), ('Genel / Diger', 'Genel / Diğer')], default='Metal Parca & Sac', max_length=100, verbose_name='Ürün Grubu'),
        ),
        migrations.AlterField(
            model_name='prototipsureci',
            name='urun_grubu',
            field=models.CharField(choices=[('Metal Parca & Sac', 'Metal Parça & Sac Şekillendirme'), ('Kondanser & Sogutma', 'Kondanser & Soğutma'), ('Kondenser & Sogutma', 'Kondanser & Soğutma (Eski)'), ('Kablo Grubu', 'Kablo Grubu & Demetleri'), ('Kalıp & Fikstür', 'Kalıp, Fikstür & Aparat'), ('Montaj ve Kaynak', 'Montaj ve Kaynak'), ('Plastik Enjeksiyon', 'Plastik Enjeksiyon'), ('Batarya & EV Bilesenleri', 'Batarya & EV Bileşenleri'), ('Genel / Diger', 'Genel / Diğer')], default='Metal Parca & Sac', max_length=100, verbose_name='Ürün Grubu'),
        ),
        migrations.AlterField(
            model_name='urunteklifsureci',
            name='urun_grubu',
            field=models.CharField(choices=[('Metal Parca & Sac', 'Metal Parça & Sac Şekillendirme'), ('Kondanser & Sogutma', 'Kondanser & Soğutma'), ('Kondenser & Sogutma', 'Kondanser & Soğutma (Eski)'), ('Kablo Grubu', 'Kablo Grubu & Demetleri'), ('Kalıp & Fikstür', 'Kalıp, Fikstür & Aparat'), ('Montaj ve Kaynak', 'Montaj ve Kaynak'), ('Plastik Enjeksiyon', 'Plastik Enjeksiyon'), ('Batarya & EV Bilesenleri', 'Batarya & EV Bileşenleri'), ('Genel / Diger', 'Genel / Diğer')], default='Metal Parca & Sac', max_length=100, verbose_name='Ürün Grubu'),
        ),
        migrations.AlterField(
            model_name='yeniurundevreyealmasureci',
            name='urun_grubu',
            field=models.CharField(choices=[('Kondanser & Sogutma', 'Kondanser & Soğutma Grubu'), ('Kondenser & Sogutma', 'Kondanser & Soğutma Grubu (Eski)'), ('Metal Parca & Sac', 'Metal Parça & Sac Şekillendirme'), ('Kablo Grubu', 'Kablo Grubu & Demetleri'), ('Kalıp & Fikstür', 'Kalıp, Fikstür & Aparat'), ('Montaj ve Kaynak', 'Montaj ve Kaynak'), ('Plastik Enjeksiyon', 'Plastik Enjeksiyon'), ('Batarya & EV Bilesenleri', 'Batarya & EV Bileşenleri'), ('Genel / Diger', 'Genel / Diğer')], default='Kondanser & Sogutma', max_length=100, verbose_name='Ürün Grubu'),
        ),
    ]
