# Generated by Django 6.0.4 on 2026-09-21 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0019_anaproje_aciklama_notu_anaproje_bolum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urunteklifadimkaydi',
            options={'ordering': ['adim__sira_no'], 'verbose_name': 'Ürün Teklif Adım Kaydı', 'verbose_name_plural': 'Ürün Teklif Adım Kayıtları'},
        ),
        migrations.AlterModelOptions(
            name='urunteklifadimtanimi',
            options={'ordering': ['sira_no'], 'verbose_name': 'Ürün Teklif Adım Tanımı', 'verbose_name_plural': 'Ürün Teklif Adım Tanımları'},
        ),
        migrations.AddField(
            model_name='urunteklifadimtanimi',
            name='adim_kodu',
            field=models.CharField(default='1', max_length=10, unique=True, verbose_name='Adım Kodu'),
        ),
        migrations.AddField(
            model_name='urunteklifadimtanimi',
            name='ana_adim_mi',
            field=models.BooleanField(default=True, verbose_name='Ana Adım mı?'),
        ),
        migrations.AddField(
            model_name='urunteklifadimtanimi',
            name='dijital_platformlar',
            field=models.TextField(blank=True, null=True, verbose_name='Dijital Platformlar'),
        ),
        migrations.AddField(
            model_name='urunteklifadimtanimi',
            name='sira_no',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Sıra Numarası'),
        ),
        migrations.AddField(
            model_name='urunteklifadimtanimi',
            name='sorumlular_raci',
            field=models.TextField(blank=True, null=True, verbose_name='Sorumlular (RACI)'),
        ),
        migrations.AddField(
            model_name='urunteklifsureci',
            name='guncel_adim_kodu',
            field=models.CharField(default='1', max_length=10, verbose_name='Güncel Adım Kodu'),
        ),
        migrations.AlterField(
            model_name='urunteklifadimkaydi',
            name='adim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_takip.urunteklifadimtanimi', verbose_name='Süreç Adımı'),
        ),
        migrations.AlterField(
            model_name='urunteklifadimtanimi',
            name='adim_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Adım Numarası'),
        ),
        migrations.AlterField(
            model_name='urunteklifadimtanimi',
            name='faz',
            field=models.CharField(choices=[('FAZ1', 'Faz 1: RFQ Alımı & Ön Fizibilite (Adım 1-4C)'), ('FAZ2', 'Faz 2: Maliyet & Fiyatlandırma (Adım 5-9C)'), ('FAZ3', 'Faz 3: Yönetim Onayı & Müşteri Müzakeresi (Adım 10-15C)'), ('FAZ4', 'Faz 4: Teklif Sonucu, Devreye Alma & Kapanış (Adım 16-16C)')], default='FAZ1', max_length=10, verbose_name='Süreç Fazı'),
        ),
        migrations.AlterField(
            model_name='urunteklifadimtanimi',
            name='sorumlular',
            field=models.TextField(blank=True, null=True, verbose_name='Sorumlular (Eski Uyum)'),
        ),
    ]
