# Generated by Django 6.0.4 on 2026-09-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0020_alter_urunteklifadimkaydi_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozlesmeadimtanimi',
            name='dijital_platformlar',
            field=models.TextField(blank=True, null=True, verbose_name='Dijital Platformlar'),
        ),
        migrations.AddField(
            model_name='sozlesmeadimtanimi',
            name='sorumlular_raci',
            field=models.TextField(blank=True, null=True, verbose_name='Sorumlular (RACI)'),
        ),
        migrations.AlterField(
            model_name='sozlesmeadimtanimi',
            name='faz',
            field=models.CharField(choices=[('FAZ1', 'Faz 1: Talep Kaydı & İnceleme (Adım 1-3)'), ('FAZ2', 'Faz 2: Değerlendirme & Yetkili Makam Kararı (Adım 4-5)'), ('FAZ3', 'Faz 3: Müşteri Müzakeresi & Mutabakat Kontrolü (Adım 6-7)'), ('FAZ4', 'Faz 4: Yetkili İmza & Yürürlük Takibi (Adım 8-9)')], default='FAZ1', max_length=10, verbose_name='Süreç Fazı'),
        ),
    ]
