# Generated by Django 6.0.4 on 2026-09-21 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_takip', '0021_sozlesmeadimtanimi_dijital_platformlar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusteriAdayi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=150, verbose_name='Yetkili Adı Soyadı')),
                ('unvan', models.CharField(blank=True, max_length=150, null=True, verbose_name='Yetkili Unvanı / Görevi')),
                ('sirket_adi', models.CharField(max_length=200, verbose_name='Firma / Şirket Adı')),
                ('sektor', models.CharField(choices=[('Beyaz Eşya', 'Beyaz Eşya'), ('Otomotiv', 'Otomotiv'), ('İklimlendirme & Soğutma', 'İklimlendirme & Soğutma'), ('Elektronik & Enerji', 'Elektronik & Enerji'), ('Genel Endüstri', 'Genel Endüstri'), ('Diğer', 'Diğer')], default='Beyaz Eşya', max_length=100, verbose_name='Sektör')),
                ('ulke', models.CharField(default='Almanya', max_length=100, verbose_name='Ülke')),
                ('sehir', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir / Bölge')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Adres Detayı')),
                ('eposta', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Posta Adresi')),
                ('telefon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('web_sitesi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Web Sitesi')),
                ('kanal', models.CharField(choices=[('Pazar Ziyareti', 'Pazar Ziyareti'), ('Fuar & Etkinlik', 'Fuar & Etkinlik'), ('Web Sitesi / Dijital', 'Web Sitesi / Dijital'), ('Müşteri Referansı', 'Müşteri Referansı'), ('Doğrudan Temas', 'Doğrudan Temas / Soğuk Arama'), ('LinkedIn / Sosyal Medya', 'LinkedIn / Sosyal Medya'), ('B2B Portal', 'B2B Portal'), ('Diğer', 'Diğer')], default='Pazar Ziyareti', max_length=100, verbose_name='Temas Kanalı')),
                ('kaynak', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detay Kaynak / Kampanya')),
                ('durum', models.CharField(choices=[('YENI', 'Yeni Aday'), ('ILETISIMDE', 'İletişimde / İlk Temas'), ('NITELIKLI', 'Nitelikli Aday (MQL/SQL)'), ('TEKLIF_ASAMASINDA', 'Teklif Aşamasında'), ('DONUSTURULDU', 'Müşteriye Dönüştürüldü'), ('KAYBEDILDI', 'Kayıp / Pasif')], default='YENI', max_length=30, verbose_name='Aday Durumu')),
                ('oncelik', models.CharField(choices=[('SICAK', 'Yüksek (Sıcak)'), ('ILIK', 'Orta (Ilık)'), ('SOGUK', 'Düşük (Soğuk)')], default='ILIK', max_length=20, verbose_name='Öncelik Seviyesi')),
                ('tahmini_potansiyel_ciro', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Tahmini Yıllık Potansiyel (€)')),
                ('ilgili_urun_gruplari', models.CharField(blank=True, max_length=255, null=True, verbose_name='İlgilendiği Ürün Grupları')),
                ('etiketler', models.CharField(blank=True, max_length=255, null=True, verbose_name='Etiketler (virgülle ayırın)')),
                ('atanan_sorumlu', models.CharField(default='Buse Nur BALTACIOĞLU', max_length=100, verbose_name='Atanan Pazarlama/Satış Sorumlusu')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama / İlk Notlar')),
                ('donusturme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Dönüştürme Tarihi')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('donusturulen_musteri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaynak_adaylar', to='crm_takip.musterikarti', verbose_name='Dönüştürülen Müşteri Portföy Kartı')),
            ],
            options={
                'verbose_name': 'Müşteri Adayı',
                'verbose_name_plural': 'Müşteri Adayları (Leads)',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='MusteriAdayiNotu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_tipi', models.CharField(choices=[('NOT', 'Genel Not'), ('TELEFON', 'Telefon Görüşmesi'), ('TOPLANTI', 'Toplantı / Görüşme'), ('EPOSTA', 'E-Posta Gönderimi / Yanıtı'), ('ZIYARET', 'Saha / Fabrika Ziyareti'), ('DURUM_DEGISIKLIGI', 'Durum Güncellemesi'), ('DONUSTURME', 'Müşteriye Dönüştürme')], default='NOT', max_length=30, verbose_name='Aktivite Tipi')),
                ('baslik', models.CharField(max_length=200, verbose_name='Aktivite Başlığı')),
                ('icerik', models.TextField(verbose_name='Detay / İçerik')),
                ('ekleyen', models.CharField(default='Buse Nur BALTACIOĞLU', max_length=100, verbose_name='Ekleyen Kişi')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Aktivite Tarihi')),
                ('adayi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to='crm_takip.musteriadayi', verbose_name='Müşteri Adayı')),
            ],
            options={
                'verbose_name': 'Müşteri Adayı Aktivite Notu',
                'verbose_name_plural': 'Müşteri Adayı Aktivite Notları',
                'ordering': ['-tarih', '-id'],
            },
        ),
    ]
